okfn-brasil/querido-diario

data_collection/gazette/gazette/spiders/to_palmas.py, data_collection/requirements.txt
implementação inicial crawler para o diário oficial do executivo de Palmas-TO.
Duvidas:
1 - Pretende salvar o numero do DO?
2 - Pretende salvar o numero do suplemento?
=> implementacao inicial crawler Palmas/TO - DO do executivo

CITIES.md, CONTRIBUTING.md
Moving the issue https://github.com/okfn-brasil/diario-oficial/issues/48 to a file to make it easier for everybody to edit it.
=> Add CITIES.md file to help us track the work to be done

CITIES.md
Thanks @anapaulagomes https://github.com/okfn-brasil/diario-oficial/issues/48#issuecomment-392259883
=> Update status of Feira de Santana (BA)

CITIES.md, processing/data_collection/gazette/spiders/pr_foz_do_iguacu.py
Foz do Iguaçu is the 97th largest GDP, but 107th largest population (sorry, I wasn't sure about the criterion)
- [Proof of legislature power in these documents](http://www.pmfi.pr.gov.br/ArquivosDB;jsessionid=9be543a88bd7e52927e641fe690e?idMidia=104275)
- [Special Edition Example](http://www.pmfi.pr.gov.br/ArquivosDB?idMidia=61569)
=> Spider for Foz do Iguaçu/PR

CITIES.md, processing/data_collection/gazette/spiders/am_manaus.py
Hey people,
In this PR we add the spider to collect data from [Manaus/AM gazette](http://dom.manaus.am.gov.br/diario-oficial-de-manaus/).
=> Add spider for Manaus/AM

CITIES.md, processing/data_collection/gazette/spiders/ce_fortaleza.py
In this PR we add the spider to collect data from [Fortaleza/CE gazette](http://apps.fortaleza.ce.gov.br/diariooficial/)
=> Add spider for Fortaleza/CE

CITIES.md, processing/data_collection/gazette/spiders/sp_guaruja.py
[Examplo de diário contendo atos de ambos os poderes](http://www.guaruja.sp.gov.br/wp-content/uploads/2017/05/06-07-2016.pdf)
[Diário oficial dividido em 3 partes](http://www.guaruja.sp.gov.br/index.php/fevereiro2017/)
[Exemplo de mais de um link por dia/linha](http://www.guaruja.sp.gov.br/index.php/marco2018/)
=> Add Guaruja/SP spider

processing/data_collection/gazette/spiders/pr_curitiba.py
@antoniovendramin 's pull request (#42) was already merged when @rennerocha
offered a valuable code review. This commit addresses the concerns
raised there:
* Avoid non-meaningful varibale names
* Reduce complexity of the spider
* Implement a date validation to avoid attempting to scrap future
gazettes
In addition:
* Sort and clean up imports
* Replace string format by f-string
* Cleanup minor details
=> Refactor Curitiba spider

CITIES.md, processing/data_collection/gazette/spiders/pr_cascavel.py
* Update CITIES.MD
* Add pr_cascavel.py
=> Add spider for Cascavel/PR

CITIES.md
Getting started Limeira Spider
=> Update CITIES.MD Adding Limeira Spider

processing/tests/gazette/data/test_bidding_exemption_parsing.py
This should fix the travis build.
=> Format file from test suite

.pre-commit-config.yaml, processing/requirements.txt, processing/tests/gazette/data/test_bidding_exemption_parsing.py
=> Use latest black version

CITIES.md
According to PR, everything is ok! 
https://github.com/okfn-brasil/diario-oficial/pull/83
=> Change Status - Maringá/PR

README.md
It's a small change, feel free to decline or edit.
=> Add more instructions to execute the spiders

processing/data_collection/gazette/spiders/sc_florianopolis.py
- Fix spider pagination order - ac7e484
- Ignore gazettes before the start_date variable - 4246a1e
=> Fix pagination order - sc_florianopolis

CITIES.md
Aqui faço a remoção da coluna de _parsers_ já que não faz mais parte do objetivo do projeto
=> Remove parser column from CITIES.md

processing/data_collection/gazette/pipelines.py
Updates the `ExtractTextPipeline` class to extract the data from odt files
=> pipelines.py: odt support

processing/data_collection/gazette/pipelines.py
For now, integrity error will be suppressed, and a warning log message will be shown
Fixes #145
=> Handle Integrity Error for duplications

.pre-commit-config.yaml, processing/Dockerfile, processing/data_collection/gazette/settings.py
Dockerfile references apache tika from unicamp FTP host
This commit changes apache tika download from unicamp FTP to
root Apaches download URLs
Closes #167
=> Fix apache tika download reference

README.md
As requested in #171 , this is the documentation I came up with.
=> Add docs for troubleshooting "Permission denied" error

CITIES.md, processing/data_collection/gazette/spiders/ba_vitoria_da_conquista.py
Originally, I submitted this as https://github.com/okfn-brasil/diario-oficial/pull/100, but I had some technical problems with git, so here it is again.
=> Add spider for Vitória da conquista/BA and update CITIES.md

processing/data_collection/gazette/pipelines.py
Just a small improvement
It wasn't totally clear to me that the file already existed on the database.
=> Update database warning message

CITIES.md
=> Check Bauru-SP

CITIES.md, processing/data_collection/gazette/spiders/sp_jau.py
Spider for gazettes of Jaú - SP
=> Jaú Gazette

processing/data_collection/gazette/spiders/mg_itauna.py
This PR adds a spider for Itaúna/MG.
For being my first contribution I apologize for any mistakes.
=> Adding spider for Itauna,MG

processing/data_collection/gazette/spiders/al_maceio.py
The main branch has a file that triggers a lint error.
This PR fixes that.
=> Fix linting error

processing/data_collection/gazette/spiders/rj_nova_iguacu.py
These files weren't formatted with black and were breaking other unrelated PRs.
=> Fix file formatting with black

processing/data_collection/gazette/spiders/rn_natal.py
Based on the discussions on #247 , I did a change in Natal-RN spider and introduce a smarter procedure stop sending more requests than we need if we want to get only gazettes newer than an specific date.
Comparing execution time and number of requests we can see a huge difference between the code in `main` and this PR code:
For sites where we can decide to send requests providing search arguments (like year and month), this approach should be enough to make them faster for incremental scrapes.
=> Natal-RN - Limit requests according to start date argument provided

processing/data_collection/gazette/spiders/rj_rio_de_janeiro.py
- Add date filtering
- Fix broken spider
=> Refactor Rio de Janeiro-RJ spider to allow date filtering

CITIES.md, processing/data_collection/gazette/spiders/df_brasilia.py
This finishes the spider for Brasília.
Some stuff that was requested by reviewers at the original PR #57 was corrected. 
This is motivated by #221 .
Closes #183  .
=> Add df_brasilia spider

processing/data_collection/gazette/pipelines.py, processing/data_collection/gazette/settings.py, processing/data_collection/gazette/spiders/base.py
For the sake of DRY, I added an Item Pipeline for setting default values for `territory_id` and `scraped_at`. 
Any comments are welcome.
=> Add `DefaultValuesPipeline`

processing/data_collection/gazette/spiders/pr_curitiba.py
=> Fix pr_curitiba

processing/data_collection/gazette/spiders/pr_curitiba.py
This was breaking CI checks on unrelated PRs
=> Fix file formatting

CITIES.md, processing/data_collection/gazette/spiders/sp_piracicaba.py
=> Add Piracicaba-SP spider

processing/Dockerfile, processing/data_collection/gazette/pipelines.py, processing/data_collection/gazette/settings.py, processing/requirements.in, processing/requirements.txt
Processing of content of downloaded files will be done in a separated pipeline, so we don't need it in this part of the process.
=> Remove text extraction from pipeline

processing/data_collection/gazette/pipelines.py
Fix #313 
Some cities have more than one file for the same gazette edition. We
need to store uploaded file information (like URL, path and checksum)
for all of them. We were storing just the information of the first file
available (which is ok for the majority of the cities that have only one
file per date), but fails if we have more files available.
=> Store all files information available for a date

CITIES.md, processing/data_collection/gazette/spiders/rn_mossoro.py
=> Adding a spider for RN - Mossoró

CITIES.md, processing/data_collection/gazette/spiders/pa_ananindeua.py
Hello :wave: 
This PR add spider for Ananindeua - Para
=> Add spider for Ananindeua/PA

README.md, windows_users.md
After our hackaton 2 months ago, we got a group of Windows Users and after some meetings we made it work. This is a Windows setup guide so we can help new people to contribute with the project.
Thanks @cecivieira for reviewing the text and testing it in another computer.
=> Creating a guide to help Windows User to do their setup

processing/data_collection/gazette/spiders/pb_campina_grande.py
It finishes `pb_campina_grande` spider, as part of #221. Closes #115 and #116 .
=> Finish spider for "Campina Grande/PB" 

CITIES.md, processing/data_collection/gazette/spiders/rs_canoas.py
I merged the code from #91 by @Lrcezimbra into main and fixed the case of parsing a day without gazette.
This is working and ready to be merged.
Fixes #10
=> Add crawler for Canoas/RS

data_collection/requirements.in, data_collection/requirements.txt
=> Add Jinja2 to requirements.in/txt

.gitignore, README.md, data_collection/gazette/settings.py
Closes #343 and makes a small adjustment in the README instructions (processing directory doesn't exist anymore)
=> Fix FILES_STORE and README

CONTRIBUTING.md
=> Removed Docker references from CONTRIBUTING (issue #363)

data_collection/gazette/pipelines.py, data_collection/gazette/spiders/pa_belem.py
- Improve method to obtain number of items that exists in the period
desired without relying on blocking requests
- Code formatting
- Add new field edition_number
- Filter gazettes scraped considering start_date argument
=> Review Belém-PA spider

CITIES.md, CONTRIBUTING.md, data_collection/gazette/spiders/ba_acajutiba.py, data_collection/gazette/spiders/base.py
Closes #300 
This is a new PR due to the several changes done on the project structure, check PR #330 for reference.
=> Add base spider for doem.org.br and spider for Acajutiba/BA

data_collection/gazette/spiders/ba_salvador.py
Review spider code and update it following new project structure.
=> Review of Salvador-BA spider

data_collection/gazette/spiders/go_goiania.py
Update spider to follow new project structure and add filtering by date to avoid unnecessary requests.
=> Review Goiania-GO spider

data_collection/gazette/pipelines.py
This will reduce the amount of database accesses when running spiders. When a file has the status `uptodate`, it indicates that it was already downloaded ([reference](https://docs.scrapy.org/en/latest/topics/media-pipeline.html#scrapy.pipelines.files.FilesPipeline.get_media_requests))
=> Avoid inserting info of gazettes that were already downloaded before

README.md, scripts/generate_spiders.py, scripts/spider_template.py
This script is for cases where we have a few spiders that are not complex and from the same source.
Example of a CSV file:
```
url,city,state,territory_id,start_day,start_month,start_year,base_class
http://pmXIQUEXIQUEBA.imprensaoficial.org,Xique-Xique,BA,2933604,1,1,2017,ImprensaOficialSpider
http://pmWENCESLAUGUIMARAESBA.imprensaoficial.org,Wenceslau Guimarães,BA,2933505,1,1,2017,ImprensaOficialSpider
http://pmVERACRUZBA.imprensaoficial.org,Vera Cruz,BA,2933208,1,4,2017,ImprensaOficialSpider
```
Command:
```
python generate_spiders.py new-spiders.csv
```
Example of a generated spider:
```
from datetime import date
from gazette.spiders.base import ImprensaOficialSpider
class BaGentioDoOuroSpider(ImprensaOficialSpider):
name = "ba_gentio_do_ouro"
allowed_domains = …
```
=> Create a spider generator

data_collection/gazette/spiders/al_maceio.py
- Filter by start_date
- Warning when download URL is not available
=> Refactor Maceio-AL spider

README.md
I've spotted some errors and then used the Grammarly tool to help to find other inconsistencies.
=> Readme grammar check

data_collection/gazette/spiders/rn_natal.py, data_collection/gazette/spiders/rr_boa_vista.py
Both spiders were broken. I tested it running a full crawl without downloading files and then a crawl since March 2021 downloading files (disk space issues :/ ).
Only thing worth mentioning is that for rr_boa_vista any DOWNLOAD_DELAY below 2 seconds was giving status code 429 right from the start, that's the reason behind it.
=> Fix rr_boa_vista and rn_natal spiders

README.md
Fix #367
Signed-off-by: Jonathan Schweder <jonathanschweder@gmail.com>
=> Alert that running the crawlers will be slow and explicitly mention where the files will be downloaded

CITIES.md, data_collection/gazette/spiders/sp_guaratingueta.py
Fixes for PR #403
The original author seem to have abandoned the original PR, I've pick the changes, rebase it with the current main branch and fix the code, there were one invalid regex and a collection of "or" that I change to use the `any()`built in function.
=> Add Guaratinguetá-SP spider

.github/workflows/schedule_spider.yaml, data_collection/gazette/settings.py, data_collection/requirements.in, data_collection/requirements.txt, scripts/schedule_job.py
- Create command that schedule a spider
- Add workflows to manually trigger spiders for full crawl or crawl after a date
=> Schedule job script

data_collection/gazette/spiders/df_brasilia.py
I also think the website hosting the gazettes was upgraded to https, which was causing some problems with the old url.
=> Adds start_date to Brasília Spider

data_collection/gazette/spiders/ba_feira_de_santana.py
=> Avoid redirect in the starting URL

data_collection/gazette/spiders/df_brasilia.py
=> Corrige url principal de df_brasilia

data_collection/gazette/spiders/sp_sumare.py
=> Add Sumare-SP spider

data_collection/gazette/spiders/rs_porto_alegre.py, scripts/enabled_spiders.py
- Atualiza dependências
- Adapta Porto Alegre (RS) para produção
- Adapta Curitiba (PR) para produção
- Adapta Araguaína (TO) para produção
- Adapta Jundiaí (SP) para produção
- Adapta Petrolina (PE) (DOEM) para produção
- Adapta Mossoró (RN) para produção
=> Adapta Porto Alegre (RS) para produção

data_collection/gazette/spiders/ms_campo_grande.py
é esperado dentro json da variavel **_response_** na chave **_data_** uma lista de dicionários com informações dos arquivos para serem baixados : 
mas em algumas requisições está sendo retornado um valor booleano **False** : 
o código proposto verifica se o tipo do objeto dentro de **_response['data']_** é do tipo iterável, se não for, ele finaliza a função.
=> fix typeError in Campo Grande-MS spider

data_collection/gazette/spiders/base/dosp.py, data_collection/gazette/spiders/mg_uberaba.py, scripts/enabled_spiders.py
Update spider so we can handle both versions of website in a single spider.
=> Uberaba-MG

data_collection/gazette/spiders/es_serra.py
resolve okfn-brasil/querido-diario#628
=> Add Serra-ES spider

scripts/enabled_spiders.py
Apenas habilitando spider em produção.
=> Enable Caxias do Sul-RS in production

scripts/enabled_spiders.py
Habilitando Marília-SP em produção.
=> Enable Marilia-SP in production

scripts/enabled_spiders.py
Habilitando Santo André-SP em produção.
=> Enable Santo André-SP in production

data_collection/gazette/spiders/rj_belford_roxo.py
resolve okfn-brasil/querido-diario#629
=> Add Belford Roxo-RJ spider

data_collection/gazette/spiders/sp_campinas.py
Fixing #614 using the [awesome findings](https://github.com/okfn-brasil/querido-diario/issues/614#issuecomment-1253623493) from @bbertolani
=> Fixing sp_campinas spider

data_collection/gazette/spiders/ba_acajutiba.py
Adicionando mais uma cidade da classe DoemGazetteSpider.
=> Adicionando raspador de Acajutiba BA

scripts/enabled_spiders.py
Enable the following spiders in production:
- Acajutiba-BA
- Belford Roxo-RJ
- Campinas-SP
=> Enable spiders in production

data_collection/gazette/spiders/ap_macapa.py
=> Fix macapa

data_collection/gazette/spiders/ap_macapa.py, scripts/enabled_spiders.py
<Descreva o seu Pull Request informando a issue (caso exista) que está sendo solucionada ou uma descrição do código apresentado>
=> Fix Macapá-AP and enable it in production

data_collection/gazette/spiders/ba_alagoinhas.py, data_collection/gazette/spiders/ba_campo_formoso.py, data_collection/gazette/spiders/ba_juazeiro.py, data_collection/gazette/spiders/ba_senhor_do_bonfim.py
Ajustes de 4 spiders existentes:
- `ba_juazeiro` #786
- [`log`](https://gist.github.com/ayharano/09e6953c33b7431afe849ea03e757634/raw/414c85d091de654c58a75f705e9034458b161172/ba_juazeiro.log)
- `ba_alagoinhas` #787 
- [`log`](https://gist.github.com/ayharano/09e6953c33b7431afe849ea03e757634/raw/414c85d091de654c58a75f705e9034458b161172/ba_alagoinhas.log)
- `ba_campo_formoso` #788 
- [`log`](https://gist.github.com/ayharano/09e6953c33b7431afe849ea03e757634/raw/414c85d091de654c58a75f705e9034458b161172/ba_campo_formoso.log)
- `ba_senhor_do_bonfim` #789 
- …
=> Some ba spiders adjustments

data_collection/gazette/spiders/base/aplus.py
...also small improvement in how we identify extra editions
=> Do not raise error if no gazette is returned

.github/workflows/weekly_crawl.yaml, scripts/scheduler.py
Fix #579 
Decided to run it weekly instead of monthly.
=> Weekly schedule of all enabled spiders

data_collection/gazette/spiders/al_associacao_municipios.py, data_collection/gazette/spiders/al_maceio.py, data_collection/gazette/spiders/am_associacao_municipios.py, data_collection/gazette/spiders/ba_associacao_municipios.py, data_collection/gazette/spiders/ce_associacao_municipios.py, data_collection/gazette/spiders/go_associacao_municipios_agm.py, data_collection/gazette/spiders/go_associacao_municipios_fgm.py, data_collection/gazette/spiders/mg_associacao_municipios.py, data_collection/gazette/spiders/ms_associacao_municipios.py, data_collection/gazette/spiders/mt_associacao_municipios.py, data_collection/gazette/spiders/pa_associacao_municipios.py, data_collection/gazette/spiders/pb_associacao_municipios.py, data_collection/gazette/spiders/pe_associacao_municipios.py, data_collection/gazette/spiders/pi_associacao_municipios.py, data_collection/gazette/spiders/pr_associacao_municipios.py, data_collection/gazette/spiders/rj_associacao_municipios.py, data_collection/gazette/spiders/rn_associacao_municipios.py, data_collection/gazette/spiders/ro_associacao_municipios.py, data_collection/gazette/spiders/rr_associacao_municipios.py, data_collection/gazette/spiders/rs_associacao_municipios.py, data_collection/gazette/spiders/se_associacao_municipios.py, data_collection/gazette/spiders/sp_associacao_municipios.py, data_collection/gazette/spiders/sp_macatuba.py, data_collection/gazette/spiders/sp_monte_alto.py
Substituindo URL inicial de HTTP para HTTPS. Com isso reduzimos a quantidade de requests (já que não será mais necessário um redirecionamento)
=> Use HTTPS as initial URL to reduce unnecessary redirects

data_collection/gazette/spiders/df_brasilia.py
Spider was getting all months of the desired year. We can request only the months that we are interested.
Reduzindo a quantidade de requests feita. Não há necessidade de buscar todos os meses, apenas aqueles do nosso interesse.
=> Remove unnecessary requests

data_collection/gazette/spiders/ma_aldeias_altas.py, scripts/enabled_spiders.py
Finalizando https://github.com/okfn-brasil/querido-diario/pull/518
=> Aldeias Altas - MA

data_collection/gazette/spiders/ma_aldeias_altas.py
Correção do código do spider de Aldeias Altas-MA
=> Fix Aldeias Altas-MA spider

data_collection/gazette/spiders/sp_santos.py, scripts/enabled_spiders.py
Ajusta data de inicio #845 de 2015 para 2001.
=> Ajusta data de inicio para sp_santos

.github/pull_request_template.md, docs/README.md, scripts/enabled_spiders.py
Atualiza README com seção sobre dicas de execução, adicionando flags úteis para quem desenvolve raspadores usando Scrapy
=> Atualiza README com dicas de execução

scripts/enabled_spiders.py
=> Desabilita Peritoro-MA de produção

data_collection/gazette/spiders/ma_afonso_cunha.py, data_collection/gazette/spiders/ma_axixa.py, data_collection/gazette/spiders/ma_bacuri.py, data_collection/gazette/spiders/ma_bacurituba.py, data_collection/gazette/spiders/ma_boa_vista_do_gurupi.py, data_collection/gazette/spiders/ma_centro_do_guilherme.py, data_collection/gazette/spiders/ma_duque_bacelar.py, data_collection/gazette/spiders/ma_feira_nova_do_maranhao.py, data_collection/gazette/spiders/ma_maranhaozinho.py, data_collection/gazette/spiders/ma_milagres_do_maranhao.py, data_collection/gazette/spiders/ma_nina_rodrigues.py, data_collection/gazette/spiders/ma_sao_vicente_ferrer.py, data_collection/gazette/spiders/ma_viana.py, data_collection/gazette/spiders/ma_ze_doca.py
Adição de 15 novos raspadores com com sistema replicável Siganet.
=> Adição de 15 novos raspadores Amazônia Legal [Siganet]

data_collection/gazette/spiders/pe/pe_cabrobo.py, data_collection/gazette/spiders/sp/sp_braganca_paulista.py, data_collection/gazette/spiders/sp/sp_itapevi.py, data_collection/gazette/spiders/sp/sp_rio_claro.py, data_collection/gazette/spiders/sp/sp_sao_bernardo_do_campo.py
Grupo 1 de municípios requisitados na Issue #950. 🥳 
#
Logs:
[log_sp_itapevi.txt](https://github.com/okfn-brasil/querido-diario/files/12786552/log_sp_itapevi.txt)
[log_sp_rio_claro.txt](https://github.com/okfn-brasil/querido-diario/files/12786553/log_sp_rio_claro.txt)
[log_sp_sao_bernardo_do_campo.txt](https://github.com/okfn-brasil/querido-diario/files/12786554/log_sp_sao_bernardo_do_campo.txt)
[log_pe_cabrobo.txt](https://github.com/okfn-brasil/querido-diario/files/12786555/log_pe_cabrobo.txt)
[log_sp_braganca_paulista.txt](https://github.com/okfn-brasil/querido-diario/files/12786557/log_sp_braganc …
=> [DOSP]Grupo 1 de spiders.

data_collection/gazette/spiders/ba/ba_brotas_de_macaubas.py, data_collection/gazette/spiders/ba/ba_cachoeira_2017.py, data_collection/gazette/spiders/ba/ba_cacule_2014.py, data_collection/gazette/spiders/ba/ba_camamu_2017.py, data_collection/gazette/spiders/ba/ba_catolandia_2015.py, scripts/enabled_spiders.py
resolvendo Grupo 2 da issue #947
:white_check_mark: **ba_brotas_de_macaubas**  está baixando os diários da data `2019-08-13` ate a data atual `2023-10-11`
:anger: **ba_cachoeira** está baixando os diários da data `2018-01-09` ate a data `2021-01-27` sem mais registros atualizados  e isso acontece com os outros municípios
:anger: **ba_catolandia** ultimo diário: `2020-12-29`
:anger: **ba_camamu** ultimo diário: `2020-12-31`
:anger: **ba_cacule** ultimo diario:`2020-12-30`
📝 Arquivos de Logs:
[ba_brotas_de_macaubas.txt](https://github.com/okfn-brasil/querido-diario/files/12920340/ba_brotas_de_macaubas. …
=> :books: [Revisão retroativa] Raspadores de DOEM - Grupo 2

data_collection/gazette/spiders/ba/ba_alcobaca_2017.py, data_collection/gazette/spiders/ba/ba_antonio_cardoso_2017.py, data_collection/gazette/spiders/ba/ba_banzae.py, data_collection/gazette/spiders/ba/ba_barra_do_choca_2017.py, data_collection/gazette/spiders/ba/ba_barrocas_2017.py, scripts/enabled_spiders.py
#947
Arquivos com Logs da checagem geral (scrapy crawl ba_antonio_cardoso -s LOG_FILE=ba_antonio_cardoso.txt -o 
ba_antonio_cardoso.csv)
[ba_antonio_cardoso.csv](https://github.com/okfn-brasil/querido-diario/files/12850410/ba_antonio_cardoso.csv)
[ba_antonio_cardoso.txt](https://github.com/okfn-brasil/querido-diario/files/12850412/ba_antonio_cardoso.txt)
Arquivos com Logs da checagem aleatória com start_date e end_date (2019-09-01 a 2019-11-01)
[ba_antonio_cardoso_2019(09-11).txt](https://github.com/okfn-brasil/querido-diario/files/12850430/ba_antonio_cardoso_2019.09-11.txt) …
=> Raspadores de DOEM - Grupo 1 - BA

data_collection/gazette/spiders/ba/ba_alcobaca.py, scripts/enabled_spiders.py
A cidade já havia sido testada em #964, a PR apenas adiciona um ajuste
=> Habilita Alcobaça-BA em produção

data_collection/gazette/spiders/pr/pr_primeiro_de_maio.py
=> adiciona raspador para pr primeiro de maio

data_collection/gazette/spiders/ba/ba_monte_santo.py, data_collection/gazette/spiders/ba/ba_morro_do_chapeu.py, data_collection/gazette/spiders/ba/ba_santa_luzia.py
Issue #985 
Adicionei raspadores da lista de PR4:
Monte Santo - BA
Morro do Chapéu - BA
Santa Luzia - BA
=> Adição das cidades de PR4

data_collection/gazette/spiders/ba/ba_catu_2014.py, data_collection/gazette/spiders/ba/ba_floresta_azul_2017.py, data_collection/gazette/spiders/ba/ba_formosa_do_rio_preto.py
Faz um ajuste em no raspador para Formosa do Rio Preto-BA e finaliza revisão retroativa de #947
=> Revisa alguns raspadores

scripts/enabled_spiders.py
Devido a problema encontrado no raspador (#1052)
=> Remove cidade da lista de spiders habilitados

data_collection/gazette/spiders/mg/mg_belo_horizonte.py
=> Obter o prefixo de download

data_collection/gazette/spiders/sp/sp_tremembe.py
Boletim disponibilizado na plataforma https://www.imprensaoficialmunicipal.com.br/tremembe.
[log_sp_tremembe.txt](https://github.com/okfn-brasil/querido-diario/files/14156951/log_sp_tremembe.txt)
[log_sp_tremembe.csv](https://github.com/okfn-brasil/querido-diario/files/14156952/log_sp_tremembe.csv)
resolve #1071
=> new spider Tremembé/SP

data_collection/gazette/spiders/sp/sp_monteiro_lobato.py
O municipio disponibiliza através da plataforma imprensaoficialmunicipal.com.br, portanto foi utilizado a classe DospGazetteSpider.
[log_sp_monteiro_lobato.txt](https://github.com/okfn-brasil/querido-diario/files/14156923/log_sp_monteiro_lobato.txt)
[log_sp_monteiro_lobato.csv](https://github.com/okfn-brasil/querido-diario/files/14156924/log_sp_monteiro_lobato.csv)
resolve #1071
=> new spider Monteiro Lobato/SP

data_collection/gazette/spiders/sp/sp_macatuba.py
[sp_macatuba.csv](https://github.com/okfn-brasil/querido-diario/files/14672477/sp_macatuba.csv)
[sp_macatuba.log](https://github.com/okfn-brasil/querido-diario/files/14672478/sp_macatuba.log)
=> [novo spider] Macatuba - SP

data_collection/gazette/spiders/sp/sp_cunha.py
Boletim disponibilizado a partir do modelo DOSP. Foi utilizada a classe DospGazetteSpider.
[log_sp_cunha.txt](https://github.com/okfn-brasil/querido-diario/files/14156896/log_sp_cunha.txt)
[log_sp_cunha.csv](https://github.com/okfn-brasil/querido-diario/files/14156897/log_sp_cunha.csv)
resolve #1071
=> new spider Cunha/SP

docs/CONTRIBUTING-en-US.md, docs/CONTRIBUTING.md, docs/README-en-US.md, docs/README.md, docs/TROUBLESHOOTING-en-US.md, docs/TROUBLESHOOTING.md
- Issue #881 
- Adicionei sobre o WSL
- Modifiquei os arquivos de Troubleshooting
- Incluí o Tutorial do Raspador da Escola de Dados no Início
=> Melhorias de documentação #881

docs/CONTRIBUTING.md
Este Pull Request introduz uma melhoria no arquivo CONTRIBUTING.md, adicionando uma seção que vincula diretamente às metas do repositório no GitHub. A inclusão deste link visa tornar as metas mais acessíveis e visíveis para os contribuidores, incentivando uma maior participação alinhada com os objetivos do projeto Querido Diário.
- Adicionada a seção "Metas do Repositório" em CONTRIBUTING.md.
- Incluído link para as [metas do repositório](https://github.com/okfn-brasil/querido-diario/milestones) que direciona os contribuidores para uma visão clara dos objetivos atuais do projeto.
Closes #499.
=> Adiciona link para as metas no CONTRIBUTING.md (Issue #499)

.github/ISSUE_TEMPLATE/revisao_retroativa.yaml, .github/pull_request_template.md, data_collection/gazette/settings.py, data_collection/templates/spiders/qdtemplate.tmpl, docs/CONTRIBUTING.md, docs/README.md
Esta PR faz 3 coisas principalmente: 
1. Atualiza o pull_request_template.md, conforme:
- nova documentação oficial
- contribuições feitas por @Winzen em #864 
(obrigada! ❤️ )
- contribuições feitas por @claromes em #928 
(obrigada! 💟 ) 
2. Corrige algumas referências de links para páginas de documentação que não existem mais visto que ela foi atualizada
3. Personaliza um recurso do Scrapy, adicionando o recurso de template para raspadores do QD e ensina como usá-lo no README.
=> Atualiza documentações do repositório

data_collection/gazette/spiders/base/diariooficialbr.py, data_collection/gazette/spiders/to/to_aguiarnopolis.py, data_collection/gazette/spiders/to/to_camposlindos.py, data_collection/gazette/spiders/to/to_goiatins.py, data_collection/gazette/spiders/to/to_peixe.py, data_collection/gazette/spiders/to/to_tocantinia.py
Issue: https://github.com/okfn-brasil/querido-diario/issues/1017
- Inclusão de nova spider base para o diariooficialbr.
- Inclusão de 5 novos municípios que utilizam a nova spider base.
- A base spider foi desenvolvida e a extração de cada novo município foi feita utilizando essa nova base.
=> [Novo spider base]: diariooficialbr

data_collection/gazette/spiders/mg/mg_uberlandia.py
O raspador para uberlândia-MG passou recusar requisição com erro 403, foi necessário adicionar user-agent para corrigir. Além disso, foi percebido que o raspador coletava o HTML da página intermediária e não o arquivo do diário de fato. Foi corrigido pela PR. 
[uberlandia-completo.txt](https://github.com/okfn-brasil/querido-diario/files/15016722/uberlandia-completo.txt)
[uberlandia-completo.csv](https://github.com/okfn-brasil/querido-diario/files/15016733/uberlandia-completo.csv)
[uberlandia-ultimo.txt](https://github.com/okfn-brasil/querido-diario/files/15016737/uberlandia-ultimo …
=> Atualiza raspador de Uberlândia-MG

data_collection/gazette/spiders/rs/rs_marau.py, data_collection/gazette/spiders/rs/rs_santa_clara_do_sul.py, data_collection/gazette/spiders/rs/rs_tres_arroios.py
- Marau-RS
[rs_marau-completo.csv](https://github.com/okfn-brasil/querido-diario/files/15255363/rs_marau-completo.csv) | [rs_marau-completo.txt](https://github.com/okfn-brasil/querido-diario/files/15255364/rs_marau-completo.txt)
[rs_marau-periodo.csv](https://github.com/okfn-brasil/querido-diario/files/15255365/rs_marau-periodo.csv) | [rs_marau-periodo.txt](https://github.com/okfn-brasil/querido-diario/files/15255366/rs_marau-periodo.txt)
- Santa Clara do Sul-RS
[rs_santa_clara_do_sul-completo.csv](https://github.com/okfn-brasil/querido-diario/files/15255367/rs_santa_clara_do_sul- …
=> add: raspadores para Marau-RS, Santa Clara do Sul-RS, Três Arroios-RS

data_collection/gazette/database/models.py
Ao modificar o `TERRITORY_ID` ou o `start_date` de um raspador, um
erro ocorria pois o raspador era detectado como um novo raspador e
a nova entrada no banco era bloqueada pelo nome como chave
primária.
Agora, atualizações em `TERRITORY_ID` e `start_date` podem ser
realizadas e os campos serão atualizados no banco sem a tentativa
de inserção de novo registro.
=> Corrige modificação do banco em atualização de raspadores

data_collection/gazette/spiders/base/adiarios_v1.py, data_collection/gazette/spiders/ce/ce_caucaia.py, data_collection/gazette/spiders/ce/ce_juazeiro_do_norte.py, data_collection/gazette/spiders/ma/ma_buriticupu.py, data_collection/gazette/spiders/ma/ma_itapecuru_mirim.py
Esse PR realiza modificações alinhadas com a meta de expansão para as 100 maiores cidades da Amazônia Legal.
A saber:
* Adiciona o spider base para o sistema aDiarios
* Atualiza o spider de Cacucaia/CE, que passou a usar o sistema aDiarios
* Cria o spider de Buriticupu-MA com a base aDiarios
* Cria o spider de Itapecuru Mirim-MA com a base aDiarios
Eu executei a extração completa para as três cidades e houve um único erro.
O erro foi do diário de Caucaia/CE do dia 06/11/2014, que aponta para um link que não possui arquivo, o link em questão é: …
=> Base adiarios

data_collection/gazette/spiders/ma/ma_afonso_cunha.py, data_collection/gazette/spiders/ma/ma_coroata.py
Experimenta corrigir um item da lista de casos em #1172.
=> Habilita proxy em Afonso Cunha-MA

data_collection/gazette/spiders/ma/ma_afonso_cunha.py, data_collection/gazette/spiders/ma/ma_axixa.py, data_collection/gazette/spiders/ma/ma_boa_vista_do_gurupi.py, data_collection/gazette/spiders/ma/ma_centro_do_guilherme.py, data_collection/gazette/spiders/ma/ma_coroata.py, data_collection/gazette/spiders/ma/ma_maranhaozinho.py, data_collection/gazette/spiders/ma/ma_nina_rodrigues.py, data_collection/gazette/spiders/ma/ma_sao_vicente_ferrer.py, data_collection/gazette/spiders/ma/ma_viana.py, data_collection/gazette/spiders/ma/ma_ze_doca.py
=> Habilita proxy em raspadores do Maranhão

data_collection/gazette/spiders/rn/rn_mossoro_2023.py
resolve #1174 
[rn_mossoro_2023-completa.log](https://github.com/user-attachments/files/15905271/rn_mossoro_2023-completa.log)
[rn_mossoro_2023-completa.csv](https://github.com/user-attachments/files/15905273/rn_mossoro_2023-completa.csv)
[rn_mossoro_2023-intervalo.log](https://github.com/user-attachments/files/15905274/rn_mossoro_2023-intervalo.log)
[rn_mossoro_2023-intervalo.csv](https://github.com/user-attachments/files/15905275/rn_mossoro_2023-intervalo.csv)
[rn_mossoro_2023-ultimo-dia.log](https://github.com/user-attachments/files/15905276/rn_mossoro_2023-ultimo-dia.log)
[rn_mossoro_2023-ultimo-dia.csv](https://github.com/user-attachments/files/15905277/rn_mossoro_2023-ultimo-dia.csv)
=> Atualiza raspador para Mossoró-RN

data_collection/gazette/spiders/ba/ba_jeremoabo.py, data_collection/gazette/spiders/ma/ma_itapecuru_mirim.py, data_collection/gazette/spiders/rs/rs_candelaria.py, data_collection/gazette/spiders/sp/sp_barbosa.py, data_collection/gazette/spiders/sp/sp_lavinia.py, data_collection/gazette/spiders/sp/sp_marilia.py, data_collection/gazette/spiders/sp/sp_sarutaia.py, data_collection/gazette/spiders/to/to_campos_lindos.py
=> Padroniza o layout de raspadores para municípios replicados com modificações

data_collection/gazette/spiders/sp/sp_alvares_florence.py
> Arquivos de saída de testes foram ignorados no commit.
Adicionado o spider para o município Alvares Florence - SP.
=> spider: sp_alvares_florence

data_collection/gazette/spiders/base/dioenet.py, data_collection/gazette/spiders/pr/pr_marilandia_do_sul.py, data_collection/gazette/spiders/rj/rj_nova_friburgo.py, data_collection/gazette/spiders/rj/rj_sumidouro.py, data_collection/gazette/spiders/sp/sp_taubate.py
=> Adiciona novo spider base dioenet

data_collection/gazette/spiders/ba/arataca.py, data_collection/gazette/spiders/ba/ba_antas.py, data_collection/gazette/spiders/ba/ba_apuarema.py, data_collection/gazette/spiders/ba/ba_aracas.py, data_collection/gazette/spiders/ba/ba_aramari.py
- [ x ] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.
- [ x ] O(s) raspador(es) adicionado(s) tem os [atributos de classe exigidos](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#UFMunicipioSpider).
- [ x ] O(s) raspador(es) adicionado(s) cria(m) objetos do tipo Gazette coletando todos [os metadados necessários](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/raspadores.html#Gaze …
=> Adicionado raspadores do municípios de Antas, Apuarema, Araças,  Aramari e Arataca

data_collection/gazette/spiders/to/to_tocantinopolis.py
<Descreva o seu Pull Request informando a issue (caso exista) que está sendo solucionada ou uma descrição do código apresentado>
=> adiciona raspador tocantinopolis

data_collection/gazette/spiders/ma/ma_maracacume.py
- [ X] É um *layout* padrão e todos os municípios adicionados usam a [classe de spider base](https://github.com/okfn-brasil/querido-diario/tree/main/data_collection/gazette/spiders/base) adequada para o padrão.
- [ X] Não utilizo `custom_settings` em meu raspador.
- [ X] Uma coleta-teste **completa** foi feita. Os arquivos de `.log` e `.csv` deste teste estão anexados na PR.
[log_ma_maracacume.txt](https://github.com/user-attachments/files/17549187/log_ma_maracacume.txt)
[ma_maracacume.csv](https://github.com/user-attachments/files/17549188/ma_maracacume.csv)
- [ X] Eu …
=> Novo municipio Maracacume

data_collection/gazette/spiders/base/sai.py
Implementação de dlay de download em raspador base SAI que causava erro no download de arquivos.
=> Fix issue 1175

data_collection/gazette/spiders/rj/rj_niteroi.py
[completo.csv](https://github.com/user-attachments/files/17484305/completo.csv)
[log_completo.log](https://github.com/user-attachments/files/17484438/log_completo.log)
[ultima.csv](https://github.com/user-attachments/files/17484342/ultima.csv)
[log_ultimo.log](https://github.com/user-attachments/files/17484440/log_ultimo.log)
[intervalo.csv](https://github.com/user-attachments/files/17484384/intervalo.csv)
[log_intervalo.log](https://github.com/user-attachments/files/17484439/log_intervalo.log)
Resolve issue #1301
=> Manutenção: Corrigir raspador de Niterói-RJ

data_collection/gazette/spiders/ap/ap_tartarugalzinho.py, data_collection/gazette/spiders/pa/pa_garrafao_do_norte.py, data_collection/gazette/spiders/pe/pe_moreilandia.py, data_collection/gazette/spiders/rn/rn_santa_cruz.py, data_collection/gazette/spiders/rn/rn_sao_francisco_do_oeste.py, data_collection/gazette/spiders/rn/rn_taboleiro_grande.py
As spiders adicionadas nesta PR foram criadas com um *script* criador de código, por isso toda essa PR deve ser revisada em todos os detalhes e também ser testada. 
Fica a cargo da pessoa revisora verificar a lista de [validações para contribuições](https://github.com/okfn-brasil/querido-diario/blob/main/.github/pull_request_template.md).
=> Adiciona 6 novos raspadores

data_collection/gazette/spiders/ms/ms_deodapolis.py, data_collection/gazette/spiders/ms/ms_gloria_de_dourados.py, data_collection/gazette/spiders/ms/ms_paranhos.py, data_collection/gazette/spiders/ms/ms_rio_brilhante.py, data_collection/gazette/spiders/pr/pr_cafezal_do_sul.py, data_collection/gazette/spiders/pr/pr_carambei.py, data_collection/gazette/spiders/rs/rs_quatro_irmaos.py
As spiders adicionadas nesta PR foram criadas com um *script* criador de código, por isso toda essa PR deve ser revisada em todos os detalhes e também ser testada. 
Fica a cargo da pessoa revisora verificar a lista de [validações para contribuições](https://github.com/okfn-brasil/querido-diario/blob/main/.github/pull_request_template.md).
=> Adiciona novos 9 raspadores

data_collection/gazette/spiders/rj/rj_macae.py
resolve #1345 
[rj_macae_completo.log](https://github.com/user-attachments/files/18355796/rj_macae_completo.log)
[rj_macae_completo.csv](https://github.com/user-attachments/files/18355797/rj_macae_completo.csv)
[rj_macae_semana.log](https://github.com/user-attachments/files/18355798/rj_macae_semana.log)
[rj_macae_semana.csv](https://github.com/user-attachments/files/18355799/rj_macae_semana.csv)
[rj_macae_mes.log](https://github.com/user-attachments/files/18355800/rj_macae_mes.log)
[rj_macae_mes.csv](https://github.com/user-attachments/files/18355801/rj_macae_mes.csv)
=> Atualiza raspador para Macaé-RJ

data_collection/gazette/spiders/sp/sp_osasco.py
=> Habilita proxy em Osasco-SP

data_collection/gazette/spiders/sp/sp_jundiai.py
resolve #1342 
[sp_jundiai_periodo_1mes.csv](https://github.com/user-attachments/files/18387016/sp_jundiai_periodo_1mes.csv) | [sp_jundiai_periodo_1mes.log](https://github.com/user-attachments/files/18387015/sp_jundiai_periodo_1mes.log)
=> Atualiza raspador de Jundiaí-SP

data_collection/gazette/spiders/rj/rj_belford_roxo.py
resolve #1370 
Atualiza spider para passar a usar base instar.
[completa.csv](https://github.com/user-attachments/files/18791480/completa.csv)
[completa.log](https://github.com/user-attachments/files/18791481/completa.log)
[intervalo.csv](https://github.com/user-attachments/files/18791482/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/18791483/intervalo.log)
[ultima.csv](https://github.com/user-attachments/files/18791484/ultima.csv)
[ultima.log](https://github.com/user-attachments/files/18791485/ultima.log)
=> Atualiza spider de Belford Roxo RJ

data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
resolve #1366 
Atualiza o spider de acordo com a nova versão do portal de Angra dos Reis.
[completa.csv](https://github.com/user-attachments/files/18790920/completa.csv)
[completa.log](https://github.com/user-attachments/files/18790922/completa.log)
[intervalo.csv](https://github.com/user-attachments/files/18790923/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/18790924/intervalo.log)
[ultima.csv](https://github.com/user-attachments/files/18790925/ultima.csv)
[ultima.log](https://github.com/user-attachments/files/18790926/ultima.log)
=> Atualiza spider de Angra dos Reis - RJ #1366

data_collection/gazette/spiders/pr/pr_arapongas.py
- [last_arapongas.txt](https://github.com/user-attachments/files/18791443/last_arapongas.txt)
- [partial_arapongas.txt](https://github.com/user-attachments/files/18791445/partial_arapongas.txt)
- [partial_arapongas.csv](https://github.com/user-attachments/files/18791444/partial_arapongas.csv)
- [full_arapongas.txt](https://github.com/user-attachments/files/18791469/full_arapongas.txt)
- [full_arapongas.csv](https://github.com/user-attachments/files/18791442/full_arapongas.csv)
Resolve #1368 
Criação de spider para Arapongas - PR
=> Cria spider arapongas

data_collection/gazette/spiders/pr/pr_pinhais.py
**AO ABRIR** uma _Pull Request_ de um novo raspador (spider), marque com um X cada um dos items da checklist abaixo. Caso algum item não seja marcado, JUSTIFIQUE o motivo.
**Layout do site publicador de diários oficiais**
**Código da(s) spider(s)**
**Testes**
- [lt_pinhais.txt](https://github.com/user-attachments/files/18791152/lt_pinhais.txt)
- [partial_pinhais.txt](https://github.com/user-attachments/files/18791145/partial_pinhais.txt)
- [partial_pinhais.csv](https://github.com/user-attachments/files/18791143/partial_pinhais.csv)
- [full_pinhais.txt](https://github.com/user-attachments/files/18791087/full_pinhais.txt)
- [full_pinhais.csv](https://github.com/user-attachments/files/18791101/full_pinhais.csv)
**Verificações**
**Descrição**
Resolve #1367 …
=> Cria spider Pinhais

data_collection/gazette/spiders/sp/sp_aguas_da_prata.py
- [full_aguas_da_prata.csv](https://github.com/user-attachments/files/18833405/full_aguas_da_prata.csv)
- [full_aguas_da_prata.txt](https://github.com/user-attachments/files/18833406/full_aguas_da_prata.txt)
- [partial_aguas_da_prata.csv](https://github.com/user-attachments/files/18833408/partial_aguas_da_prata.csv)
- [partial_aguas_da_prata.txt](https://github.com/user-attachments/files/18833409/partial_aguas_da_prata.txt)
- [last_aguas_da_prata.txt](https://github.com/user-attachments/files/18833407/last_aguas_da_prata.txt)
Cria spider para Águas da Prata - SP
=> Cria spider para Águas da Prata - SP

data_collection/gazette/spiders/sp/sp_aguai.py
- [last_aguai.txt](https://github.com/user-attachments/files/18833263/last_aguai.txt)
- [partial_aguai.txt](https://github.com/user-attachments/files/18833265/partial_aguai.txt)
- [partial_aguai.csv](https://github.com/user-attachments/files/18833264/partial_aguai.csv)
- [full_aguai.txt](https://github.com/user-attachments/files/18833262/full_aguai.txt)
- [full_aguai.csv](https://github.com/user-attachments/files/18833261/full_aguai.csv)
Cria spider para a cidade de Aguaí-SP
=> Cria spider SP-Aguaí

data_collection/gazette/spiders/base/modernizacao.py
resolve #1374 
Todos os erros existentes nos logs se referem a links quebrados para PDFs nos sites das prefeituras.
Além da correção na requisição para a api de consulta mensal, também foi removido o método para validar esses links, pois já são validados no pipeline do projeto, conforme sugestão em revisão de outro PR:
[https://github.com/okfn-brasil/querido-diario/pull/1253#discussion_r1744252449](https://github.com/okfn-brasil/querido-diario/pull/1253#discussion_r1744252449)
Logs de extrações completas dos municípios que usam o base modernização:
[rj_mesquita.csv](https://github.com/user-attachments/files/18802064/rj_mesquita.csv)
[rj_mesquita.log](https://github.com/user-attachments/files/18802065/rj_mesquita.log)
[rj_miguel_pereira.csv](https://github.com/user-attachments/files/1880206 …
=> Atualiza base modernizacao
