- data_collection/gazette/gazette/spiders/sp_campinas.py
Segue uma implementação inicial do crawler para Campinas/SP.
Dúvida: o site do portal da transparência de Campinas não separa os diários dos poderes executivo e legislativo. Disponibilizam um único PDF. Como lidar com esta situação?
Acredito que várias situações semelhantes acontecerão em outras cidades.
http://www.campinas.sp.gov.br/diario-oficial/index.php
> Campinas/SP - implementação inicial

- web/pages/index.vue
Notei uma leve melhora em alguns registros localmente apenas adicionando o parâmetro "v-once" no grid. Aparentemente, o binding é desnecessário ali e, como existem muitos registros, pode ajudar.
Quando existir paginação, provavelmente ele deverá ser removido.
> adicionando v-once no grid de dispensas

- processing/data_collection/gazette/spiders/sp_campinas.py
Probably they just published a new gazette and this might be breaking our CI
> Remove max argument from Campinas Scrapy contract

- processing/data_collection/gazette/spiders/sc_florianopolis.py
- processing/database/__init__.py
- processing/requirements.txt
Yay, first lines of code in this awesome project!
Some doubts:
**~~1. About `powers` field~~**
~~Florianópolis seams to have an unique gazette for all powers (for example, in [this issue](http://www.pmf.sc.gov.br/arquivos/diario/pdf/31_05_2016_19.03.05.676c30944d7e7b1879a9ca0143e32de7.pdf) we can see in the table of contents that it covers the executive and the legislative). This I hardcoded `powers=None` – is that ok or is there a better way to record that?~~
**UPDATE** Thanks for the [tip](https://github.com/okfn-brasil/diario-oficial/pull/2#discussion_r179343101), @brunolellis : )
**~~2. About `is_extra_edition` fields~~**
~~I browsed Florianópolis portal a bit and I've found no _extra_ issues so far. Thus I also hardcoded `is_extra_edition=False` – is that ok or is there a better way …
> Add Florianópolis (SC) spider

- processing/data_collection/gazette/spiders/sp_guarulhos.py
According to Scrapy documentation, the preferred method to return the list of the Requests that will be parsed is using the method _start_requests_:
https://doc.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.Spider.start_requests
cc/ @gustavodemari
> Use the correct method for retrieving the list of initial requests

- processing/data_collection/gazette/pipelines.py
- processing/data_collection/gazette/settings.py
- processing/data_collection/gazette/spiders/base.py
- processing/data_collection/gazette/spiders/sp_guarulhos.py
First implementation of an item pipeline that will drop any item that has a date before _start_date_ parameter (sent to the spider), avoiding it to be downloaded.
Related to #39 .
cc @Irio
> Filter item by date

- processing/data_collection/gazette/spiders/sp_campinas.py
- processing/data_collection/gazette/spiders/sp_guarulhos.py
Guarulhos and Campinas added a new gazette to jan/2018 and broke our contracts.
This problem will happen again, should we avoid using an older year for the contract?
> Update Guarulhos and Campinas contracts

- processing/data_collection/gazette/spiders/ba_feira_de_santana.py
Adds spider for Feira de Santana, the princess of _sertão_. 🌵
Gazettes website: http://www.diariooficial.feiradesantana.ba.gov.br
> Add new spider for Feira de Santana/BA

- processing/data_collection/gazette/parser.py
- processing/data_collection/gazette/settings.py
As discussed in issue #15, scrapy has a bug when request URL contains query parameters.
> Overriding file_path

- processing/data_collection/gazette/spiders/rj_rio_de_janeiro.py
This PR creates a spider to crawl gazettes from Rio de Janeiro.
I don't know how to test all possible flows using scrapy contracts.
For example:
1. `no_gazette` for weekends and holidays
2. `one_gazette` when no extra edition is published
3. `multiple_gazettes` for extra editions
I thought about creating 3 functions, one for each case, and write the contract inside each callback function, but it seems overkill, doesn't it?
**PS: this PR depends on #28**
> Add Rio de Janeiro/RJ spider

- processing/data_collection/gazette/spiders/ba_feira_de_santana.py
- processing/data_collection/gazette/spiders/es_associacao_municipios.py
- processing/data_collection/gazette/spiders/go_goiania.py
- processing/data_collection/gazette/spiders/rj_rio_de_janeiro.py
- processing/data_collection/gazette/spiders/rs_caxias_do_sul.py
- processing/data_collection/gazette/spiders/rs_porto_alegre.py
- processing/data_collection/gazette/spiders/sc_florianopolis.py
- processing/data_collection/gazette/spiders/sp_campinas.py
- processing/data_collection/gazette/spiders/sp_franca.py
- processing/data_collection/gazette/spiders/sp_santos.py
- processing/data_collection/gazette/spiders/to_araguaina.py
- processing/data_collection/gazette/spiders/to_palmas.py
This PR included a spider base class that allows us to specify the start_date we want for the gazettes to be retrieved (or the ones that should be ignored):
https://github.com/okfn-brasil/diario-oficial/pull/41
I updated all existing spiders to inherit from this class. Everything will work exactly the same, but now we have the option to execute the spider passing `start_date` parameter.
> Inherit all spiders from base spider class

- .env.example
- docker-compose.yml
WSL and older docker setups may require absolute paths from host mount. Parametizing the processing folder allows to keep docker-compose.yml clean.
> paremetize processing

- CITIES.md
- processing/data_collection/gazette/spiders/pr_ponta_grossa.py
Ponta Grossa são páginas simples com a data no nome do arquivo PDF.
Legislativo e executivo são no mesmo PDF.
> Pr ponta grossa

- processing/Dockerfile
This avoids a new version of Python coming out and breaking the code, as has happened now with Python 3.7 (which our dependency Celery doesn't support), that creates the following error:
```
processing_1  | [2018-07-07 12:16:51,570: CRITICAL/MainProcess] Unrecoverable error: SyntaxError('invalid syntax', ('/usr/local/lib/python3.
7/site-packages/celery/backends/redis.py', 21, 19, 'from . import async, base\n'))
processing_1  | Traceback (most recent call last):
processing_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
processing_1  |     return obj.__dict__[self.__name__]
processing_1  | KeyError: 'backend'
processing_1  | 
processing_1  | During handling of the above exception, another exception occurred:
processing_1  | 
processing_1  | …
```
> Use Python 3.6 on processing's Dockerfile

- CITIES.md
- processing/data_collection/gazette/spiders/al_maceio.py
Maceió is the 17th largest city in Brazil by population. This spider collects data from http://www.maceio.al.gov.br/noticias/diario-oficial/.
The `parse_additional_page` callback is necessary because some gazettes have a direct link to download and others open a new page upon click. For the same reason the scrapy contracts have different values for min and max ranges, because in some cases we will have more or less requests per gazette. The value is unpredictable because the page contents change according to new gazette uploads.
> Add Maceió (AL) spider

- processing/data_collection/gazette/spiders/ba_salvador.py
For older gazettes, they have the interesting habit to put the file from a different date.
It is also not possible to discover if it is an extra edition without parsing the gazette content. It will require a custom pipeline (specific to this city) to process the file content after it passes through _PdfParsingPipeline_ .
> Salvador spider

- docker-compose.yml
This avoids `docker-compose up` failing if ran on a machine that has Postgres
running locally on the same port. As the other containers access Postgres via
Docker, they'll continue working regardless if we're exposing its port or not.
Also, if we need to access the DB for whatever reason, we can get the random IP
assigned by Docker using `docker inspect` and use it instead.
> Don't expose Postgres port in Docker

- .gitignore
- Makefile
- processing/data_collection/gazette/middlewares.py
- processing/data_collection/gazette/pipelines.py
- processing/data_collection/gazette/spiders/ba_salvador.py
- processing/data_collection/gazette/spiders/pr_cascavel.py
- processing/requirements.txt
- processing/tests/gazette/data/test_bidding_exemption_parsing.py
- processing/tests/gazette/data/test_row_update.py
- processing/tests/gazette/data/test_section_parsing.py
- processing/tests/gazette/locations/test_go_goiania.py
- processing/tests/gazette/locations/test_rs_porto_alegre.py
- processing/tests/test_tasks.py
As we chatted in #109, this PR migrates the code from unittest from pytest.
On tox, I was able to set it up, but there were many issues because the `gazette` user inside the `processing` container can't write to the `/mnt/code` volume, as it comes from the host. I found two workarounds:
1) On the `ENTRYPOINT` use the script `docker-entrypoint.sh` (below) to change the `gazette`'s user ID to the owner of the `/mnt/code` (I can't simply chown the folder because that'll alter the owner in the user's host machine). This pattern is relatively common in Dockerland.
2) Configure `tox` and `pytest` to write their files outside `/mnt/code` (e.g. in `/mnt/data/.tox`)
Both work fine, although the 1st option caused other issues because we're sharing the `.pyc` files amongst different "machines" (the …
> Use pytest

- package-lock.json
- web/Dockerfile
- web/README.md
- web/package.json
This commit simplifies the web container
* by avoiding installing npm packages globally (we can call them using npx or via npm scripts
instead)
* by using the prestart npm script to avoid the need of chaining two commands to run the server
Does that make sense, @guidiego?
> Simplify web container

- Makefile
#128 New pytest version (3.10.0) caused failure in tests (see https://github.com/pytest-dev/pytest/issues/4304). I removed the "-p no:cacheprovider" option from the command line and it worked.
I also manually removed my local docker images (python and diario-oficial*) so that it got the newest version of pytest, as in Travis.
> Fix build with the new pytest 3.10.0

- Makefile
**PIP** defaults the the package installations to a system directory, which requires root access. This is not desirable while running a setup script.
> Fix pre-commit installation in the setup

- CITIES.md
- processing/data_collection/gazette/spiders/mg_uberaba.py
- [Example](http://www.uberaba.mg.gov.br:8080/portal/acervo/portavoz/arquivos/2019/1744%20-%2002-10-2019.pdf) of gazette with executive and legislature acts.
- Two editions weren't using the same name pattern (one with an extra word "final" and other with "CONCURSOS",), but both were unique for the date, so I judged both as non-extra editions.
- The "5000" limit is a magic number to avoid pagination.
> Add Uberaba/MG spider

- processing/data_collection/gazette/spiders/ba_feira_de_santana.py
The spider wasn't handling redirects accordingly and due to this error the files were not being downloaded, causing an error on `PdfParsingPipeline`.
```
2019-11-15 18:56:29 [scrapy.downloadermiddlewares.redirect]
DEBUG: Redirecting (302) to <GET https://www.diariooficial.feiradesantana.ba.gov.br/atos/legislativo/2QU6R81932019.pdf> 
from <GET http://www.diariooficial.feiradesantana.ba.gov.br/abrir.asp?edi=567&p=2>
```
To reproduce this error, execute on master:
`
docker-compose run --rm processing bash -c "cd data_collection && scrapy crawl ba_feira_de_santana"
`
> Fix Feira de Santana's gazette download

- processing/data_collection/gazette/pipelines.py
Some gazettes have text files. This PR updates the ExtractTextPipeline pipeline step to extract data from text files.
> pipelines.py: support txt file

- processing/data_collection/gazette/spiders/base.py
Updates the FECAM spider to make it run faster. For that, instead of
return the next page after get all the gazettes files, the first request
find all the pages and returns a request object for each one. Thus,
scrapy can parallelize as much as possible.
> base.py: makes FECAM spider run faster

- processing/Dockerfile
- processing/data_collection/gazette/pipelines.py
Updates the Apache Tika version used. The old version is not available
anymore
Issue https://github.com/okfn-brasil/diario-oficial/issues/147
> Update Apache Tika

- CONTRIBUTING.md
- Makefile
Adds some helpers functions in the Makefile to open the psql, run spiders
and delete the gazette files
> Makefile: helper commands

- processing/data_collection/gazette/spiders/sc_florianopolis.py
After #139, the spider raises an exception if the spider class hasn't a start_date field
Now it's fixed with `hasattr` function.
> Fix AttributeError trying to get start_date field

- CITIES.md
- processing/data_collection/gazette/spiders/rs_gravatai.py
This PR adds a Spider for the Gravatai city.
Can someone explain me how can I check if the gazettes that I am crawling are from the legislative or executive legislature? You can check it here: https://gravatai.atende.net/?pg=diariooficial
I had two problems when working on it. First one was when I tried to do my first commit... The pre-commit hook raised me this error:
```shell
[I] ~/d/diario-oficial ∙ git commit -m 'Update Rs Gravatai docstrings'                                                                                                                                          ᚴ upstream ⚡  rs_gravatai  1M
black....................................................................Failed
hookid: black
Starting diario-oficial_postgres_1 ... done
Starting diario-oficial_redis_1    ... …
```
> Add Spider for RS Gravatai

- .github/workflows/build.yml
- Makefile
Adds github workflow to build and publish a container image. The
namespace, username and password used to publish the image in the
registry should be set in the github secrets
Issue #159
Issue #163
> build and publish container image

- .gitignore
- processing/data_collection/gazette/settings.py
- processing/requirements.txt
Adds the scrapy-deltafetch middleware. It allow us to drop item which
already has been crawled. It uses the URL to identify if an item has
already been download. Even if it can causes issues if the same URL
points to a different data in the future, it sounds reasonable to add it
to avoid waste of resources. Furthermore, it is always possible to set
the middleware to reset and allow all the item to be crawled again.
https://github.com/okfn-brasil/diario-oficial/issues/86
> scrapy-deltafetch: avoid crawl the same URL

- processing/Dockerfile
The [link](http://ftp.unicamp.br/pub/apache/tika/tika-app-1.23.jar) to download Apache Tika 1.23 is broken on Dockerfile. Can we update to 1.24?
> Update Apache Tika to 1.24 in Dockerfile

- docker-compose.yml
- processing/Dockerfile
The `env_file` option in the `docker-compose.yml` exports the envvars when running the container but not when building it.
Unfortunately, the Compose's documentation does not cover it well (or I couldn't find it there). The best I could find to link here was this note
on the [environment section](https://docs.docker.com/compose/compose-file/#environment) that tells us to use the `args` sub-option under the `build` option to define envvars.
To complement this, if no Compose is used, the `--build-arg` option of `docker build` has to be used to export envvars at build time. As specified in the [`ARG` statement documentation](https://docs.docker.com/engine/reference/builder/#arg).
> Fix LOCAL_USER_ID envvar behaviour

- Makefile
- processing/data_collection/gazette/settings.py
- processing/data_collection/gazette/spiders/base.py
Updates the FECAM spider to be a subclass of the BaseGazetteSpider
class. Thus, the user can filter the gazette items found by date. Using
the "start_date" spider argument.
Related to: https://github.com/okfn-brasil/diario-oficial/issues/172
> Fecam spider: filter item by date

- CITIES.md
- processing/data_collection/gazette/spiders/rn_natal.py
This pull request takes over development started by @dannnylo on #60 
This should fix #189
> Add spider for Natal/RN

- Makefile
- processing/data_collection/gazette/pipelines.py
- processing/requirements.txt
Adds the QueridoDiarioFilesPipeline class. A specialization of the scrapy FilesPipeline. The new class will allow the users to store in the backends available in the scrapy class but changing the directory where the file will be stored. The current version will keep all the gazettes files from the same date in the same directory.
Issue #165
> QueridoDiarioFilesPipeline class

- Makefile
One of the step ran by the "make setup" is to populate the territories
table with the content of the "territories.cvs" files. However, if the
database is already populates by some previous failed "make setup" run,
The command fails. To fix that, before start the process of build
container images and start the process, a docker-compose call is done to
remove all the container images and volume used by the services. Thus,
the "make setup" will always rebuild everything fine.
> Duplicate key when running make setup

- CITIES.md
- processing/data_collection/gazette/spiders/pa_belem.py
Add spider for Belem - Pará. Issue #182 .
I've tried to run the spider built on [PR 87](https://github.com/okfn-brasil/diario-oficial/pull/87) but it didn't work and based on the spider code I assumed that the website changed since it was built (2 years ago)
Despite that, this PR is still a WIP because I couldn't find a way to download the PDF files.
On this spider [I am using a different URL](https://sistemas.belem.pa.gov.br/diario-consulta-api/diarios) (the API one) but you can [check in here](http://sistemas.belem.pa.gov.br/diario/painel) that we can't get any pdf `href` based on the website DOM. So, as we can download the file just by clicking on the button I guess that the only possible solution that we have is to install selenium, right? Do you see any other possible solution?
As I …
> Add spider for Belem - Pará

- processing/data_collection/gazette/spiders/al_maceio.py
This PR updates Maceio-AL spider with improvements:
- Sort imports
- Replace MUNICIPALITY_ID (deprecated field) with TERRITORY_ID
- Replaced some insecure selectors
- Reorganiza pagination requests
> Update Maceio-AL spider

- CITIES.md
- processing/data_collection/gazette/settings.py
- processing/data_collection/gazette/spiders/mt_cuiaba.py
This PR adds the spider for Cuiaba-MT as requested at https://github.com/okfn-brasil/querido-diario/issues/181
The `DOWNLOAD_DELAY` setting is important because I was getting a lot of 429 responses (Too many requests). The delay did the job and the spider isn't getting 429 responses anymore
> Add Spider for Cuiaba, MT

- CITIES.md
- processing/data_collection/gazette/spiders/pi_teresina.py
Add spider for Teresina/PI [gazette](http://dom.pmt.pi.gov.br/lista_diario.php). 
The [PR #53](https://github.com/okfn-brasil/querido-diario/pull/53) is out of date and no longer works. This PR is updated with the changes that occurred on the website.
The Teresina gazette website shows the total number of diaries available and this was explored in the development of the spider
In some editions there are also attachments. All of them are recovered by the spider
Suggestions for improvement are welcome
> Add spider for Teresina/PI

- processing/data_collection/gazette/settings.py
- processing/requirements.in
- processing/requirements.txt
This middleware was introduced to avoid spiders to request data that was already requested before, reducing the amount of requests made. However, it is not certain that it will reach this goal considering that some requests may be the same but the content returned different. A better solution to reduce the number of requests may be necessary, but we will only know for sure when we start running all the spiders daily.
More about this: #219
> Remove scrapy-deltafetch middleware

- processing/data_collection/gazette/items.py
- processing/data_collection/gazette/spiders/ba_salvador.py
- processing/data_collection/gazette/spiders/ms_campo_grande.py
- processing/data_collection/gazette/spiders/sp_guaruja.py
This field was replaced by territory_id. Just a few old spiders were still using it, so it can be removed now.
> Remove unused municipality_id field

- processing/data_collection/gazette/pipelines.py
- processing/data_collection/gazette/settings.py
This settings allows to run spiders without the step that extracts content of PDF files. Useful for developing and debugging.
> Add setting to enable/disable extracting text from gazette files

- processing/data_collection/gazette/spiders/mt_cuiaba.py
All other files use it as string and to avoid errors it's best to use
the same pattern everywhere.
> TERRITORY_ID should be a string

- README.md
- processing/data_collection/gazette/spiders/base.py
Having a fixed pattern for this argument seems better when we start
scheduling hundreds of spiders daily. It also removes the dependency on
dateparser (that can have performance issues depending the format you
are trying to parse).
> Validate format of start_date argument

- processing/data_collection/gazette/items.py
- processing/data_collection/gazette/spiders/sc_florianopolis.py
- processing/database/models.py
Practically all cities provides the edition number of gazettes and we weren't collecting it.
As usually this is something easy to collect and it seems useful to be able to find a gazette with another property, we should start collecting it. 
I updated just one spider for testing, but we will need to update all spiders to include this field.
> Add edition number field

- CITIES.md
- processing/data_collection/gazette/spiders/pb_joao_pessoa.py
This finishes the spider for João Pessoa. Just a rebase and a URL change was needed.
I changed the docstring since spider contracts are not used.
Also, I think the "Special Editions" being extracted as "Extra Editions" are not correct, but I'd prefer if someone else could clarify that. I believe that special editions are editions that have a publication date outside of the normal schedule. And extra editions are editions that are published in the same date as another "already published" edition.
This is motivated by #221 .
Closes #186 .
> Add pb_joao_pessoa spider

- processing/data_collection/gazette/spiders/to_palmas.py
It includes:
- Refactor of the code to make spider simpler and removing unneeded external libraries (like requests)
- Allow date filtering using `start_date` argument to aviod unnecessary requests
> Palmas-TO spider reactor with improved date filtering

- CITIES.md
- processing/data_collection/gazette/spiders/al_associacao_municipios.py
- processing/data_collection/gazette/spiders/am_associacao_municipios.py
- processing/data_collection/gazette/spiders/ba_associacao_municipios.py
- processing/data_collection/gazette/spiders/base.py
- processing/data_collection/gazette/spiders/ce_associacao_municipios.py
- processing/data_collection/gazette/spiders/go_associacao_municipios_agm.py
- processing/data_collection/gazette/spiders/go_associacao_municipios_fgm.py
- processing/data_collection/gazette/spiders/mg_associacao_municipios.py
- processing/data_collection/gazette/spiders/ms_associacao_municipios.py
- processing/data_collection/gazette/spiders/mt_associacao_municipios.py
- processing/data_collection/gazette/spiders/pa_associacao_municipios.py
- processing/data_collection/gazette/spiders/pb_associacao_municipios.py
- processing/data_collection/gazette/spiders/pe_associacao_municipios.py
- processing/data_collection/gazette/spiders/pi_associacao_municipios.py
- processing/data_collection/gazette/spiders/pr_associacao_municipios.py
- processing/data_collection/gazette/spiders/rj_associacao_municipios.py
- processing/data_collection/gazette/spiders/rn_associacao_municipios.py
- processing/data_collection/gazette/spiders/ro_associacao_municipios.py
- processing/data_collection/gazette/spiders/rr_associacao_municipios.py
- processing/data_collection/gazette/spiders/rs_associacao_municipios.py
- processing/data_collection/gazette/spiders/se_associacao_municipios.py
- processing/data_collection/gazette/spiders/sp_associacao_municipios.py
- processing/data_collection/gazette/spiders/sp_macatuba.py
- processing/data_collection/gazette/spiders/sp_monte_alto.py
- processing/requirements.in
- processing/requirements.txt
AMUPE (Associação de Municípios de Pernambuco) has some siblings :) The base is the same and it has coverage in almost every state (as you can see [here](http://www.diariomunicipal.com.br/)). Some states have most of their cities in it, some only have a bit more than a couple. But it is something already.
Right now, I implemented all states of the Northeast Region. I'll keep updating it in the next days. And 
document whatever we feel necessary at the end.
I reeeally didn't want to update CITIES.md to include these cities. Do you have a script for that since you added Fecam, @jvanz :smile:?
And `TERRITORY_ID` is kind of a problem. Because the Gazettes are for every city in the association. I thought about allowing a list of ids and adding multiple entries in the database for every id in …
> Add SIGPub (diariomunicipal.com.br) base spider and subspiders

- processing/data_collection/gazette/spiders/sc_florianopolis.py
This PR improves how requests are made according to the start date desired, avoiding the spider to send requests that won't get gazettes from dates we are not interested. (Based on discussion in #247).
> Florianópolis-SC - Limit requests according to start date argument provided

- .gitignore
- Makefile
- processing/Dockerfile
- processing/data_collection/gazette/database/models.py
Adds a new column in the Gazette model. This column should be used by the processing pipeline to find which gazettes is pending to be ingested by the system. This is not the best solution to this, a queue system would be a better approach for instance. But for the current state of the project this will be enough.
> File processed flag

- README.md
This PR improved Troubleshooting section on README by:
- Added instruction to add user to docker group to resolv non-specific errors
- Added instruction to restore pip if need
- Removed a ambiguity in a subsection title
> Doc: Improved Troubleshooting section on README 

- processing/data_collection/gazette/database/models.py
The default value for the processed column in the database should be
false. Thus, all the files will be processed by the processing pipeline
> Default value for the processed column

- processing/data_collection/gazette/spiders/al_maceio.py
- processing/data_collection/gazette/spiders/ba_vitoria_da_conquista.py
- processing/data_collection/gazette/spiders/base.py
- processing/data_collection/gazette/spiders/go_aparecida_de_goiania.py
- processing/data_collection/gazette/spiders/go_goiania.py
- processing/data_collection/gazette/spiders/instar_base.py
- processing/data_collection/gazette/spiders/mg_contagem.py
- processing/data_collection/gazette/spiders/mg_uberaba.py
- processing/data_collection/gazette/spiders/ms_campo_grande.py
- processing/data_collection/gazette/spiders/pb_joao_pessoa.py
- processing/data_collection/gazette/spiders/pr_cascavel.py
- processing/data_collection/gazette/spiders/pr_curitiba.py
- processing/data_collection/gazette/spiders/pr_foz_do_iguacu.py
- processing/data_collection/gazette/spiders/pr_londrina.py
- processing/data_collection/gazette/spiders/pr_maringa.py
- processing/data_collection/gazette/spiders/pr_ponta_grossa.py
- processing/data_collection/gazette/spiders/ro_porto_velho.py
- processing/data_collection/gazette/spiders/rr_boa_vista.py
- processing/data_collection/gazette/spiders/rs_caxias_do_sul.py
- processing/data_collection/gazette/spiders/rs_porto_alegre.py
- processing/data_collection/gazette/spiders/sc_florianopolis.py
- processing/data_collection/gazette/spiders/sc_joinville.py
- processing/data_collection/gazette/spiders/sp_campinas.py
- processing/data_collection/gazette/spiders/sp_guaruja.py
- processing/data_collection/gazette/spiders/sp_itu.py
- processing/data_collection/gazette/spiders/sp_santos.py
- processing/data_collection/gazette/spiders/sp_sao_jose_dos_campos.py
After the spidermon configuration some spider stop working due a invalid
value for the power item field. This commit replace all these invalid
values for the value allowed by the spidermon schema
> Fix power field to the values expected by spidermon

- CONTRIBUTING.md
I could open an issue to discuss this, but I have adopted a philosophy of starting a discussion with a proposal.
I created this chapter to propose an organization for the project maintainers. The idea is that it is not legislation with multiple responsibilities, but a guide that facilitates communication and reduces rework.
I do this when we invite @giuliocc to compose our team of maintainers. :1st_place_medal:  Thus, we are growing and creating a working model to prevent distress to people as generous as Querido Diario maintainers.
"There is a criteria I call change latency, which is the round-trip time from identifying a problem to testing a solution. The faster the better. If maintainers cannot respond to pull requests as rapidly as people expect, they're not doing their job (or they …
> Inserted Guidelines to maintainers

- data_collection/gazette/pipelines.py
The integrity error raised by SQLAlchemy is launched not only when the
item is already in the database. For instance, it can also be launched
when the territories table is missing some territory ID. Thus, this
commit updates the error message and add the exception in the log
message. Thus, the users will be able to detect which kind of error
they are facing.
> Misleading error message when write in the database fails.

- data_collection/gazette/spiders/base/sigpub.py
- data_collection/requirements.in
- data_collection/requirements.txt
This library is not required as the unique spider that uses it still works without using random custom user-agents.
> Remove fake-useragent library

- data_collection/gazette/settings.py
Some gazette files are bigger enough that the default 180s value is not enough for completing the download. This will prevent that we stop getting these big gazettes.
> Increase amount of time to wait a download finish before timing out

- CITIES.md
- data_collection/gazette/spiders/sp_sao_paulo.py
Fixes #380.
Some caveats:
* I used the url scheme shown [here](https://github.com/okfn-brasil/querido-diario/issues/7#issuecomment-385122215) which directly gives the pdf, rather than serving a pdfViewer with no easy way to query the pdf file (at least I have no idea how to do it). Unfortunately, with this scheme the farthest back one can go is to July 1st, 2017.
* As already pointed in that same issue, this gazette serves each page as a separate PDF. I handled this by just getting the maximum page and returning the list of urls for each gazette (each one for a single page). But there a couple problems:
* Since the pdf for each page is saved using a hash as its name, I think this might make it more difficult to later join the pages in the correct order. So it might be interesting to …
> Add spider for São Paulo/SP

- data_collection/gazette/spiders/ba_salvador.py
The changed how the PDF URL is displayed.
After this PR is merged, we should run a full scrape for this city, so we can get gazettes that we missed in the last weeks.
> Fix selector to retrieve PDF URL for gazette

- CITIES.md
- data_collection/gazette/spiders/mg_betim.py
Created this spider with help from Giulio, Ana, Marcio and Yara. I didn't find an extra edition pattern and inside the gazette you could see that you have "ato do legislativo" and "ato do executivo" so we have both on the same gazette. I checked if it ran since 2008 and if it runs with only one page.
> Adding spider for Betim/MG

- data_collection/gazette/spiders/base/__init__.py
I found it useful to have the end_date argument for testing purposes. So you can narrow the dates that your spider works on. 
Example of use:
`scrapy crawl sp_sao_bernardo_do_campo -a start_date=2016-06-01 -a end_date=2017-08-01`
> Add spider argument: end_date

- .github/workflows/deploy.yml
This PR enables automated deployment to ScrapingHub after a push to `main` and changes on the spider's folder. It depends on configuring the secret `SHUB_APIKEY` on this repo. I couldn't find any mention of this environment variable [in the docs](https://shub.readthedocs.io/en/stable/search.html?q=SHUB_APIKEY&check_keywords=yes&area=default) but it seems to work [according to the code](https://github.com/scrapinghub/shub/blob/3ef47b018bf4f10c2045d6385a1beb6ad2e5a638/shub/config.py#L502). :shipit:
> Deploy to scrapinghub

- data_collection/gazette/spiders/pr_maringa.py
Este PR resolve a issue #465 .
Mudanças:
- O endpoint do spider `pr_maringa.py` foi atualizado para http://venus.maringa.pr.gov.br/arquivos/orgao_oficial/seleciona_ano_oom.php
- Além de uma nova URL, a formatação da página também mudou, sendo necessário atualizar a forma que o parse estava sendo realizado
> Fix spider for Maringá/PR

- data_collection/gazette/spiders/df_brasilia.py
- scripts/enabled_spiders.py
* Fix spider to use default `end_date` if not provided
* Enable it to be executed daily
> Enabling Brasilia-DF spider

- .github/workflows/periodic_crawl.yaml
Run the spiders twice a day, so we don't need to wait much time between executions in case that we don't get the gazettes of the day in the first run. This is sync with the text extraction process (that will start one hour after).
> Update action to run spider twice a day

- data_collection/gazette/spiders/pe_recife.py
Adiciona o raspador para o [sistema novo que contém as publicações atuais de Recife (PE)](https://dome.recife.pe.gov.br/dome/).
Para isso, o antigo raspador teve seu nome modificado para "pe_recife_acervo_2015_a_2020" e o novo passa a ter o nome "pe_recife", sendo o raspador principal.
Também foram adicionados os atributos de classe `start_date` e `end_date` no raspador antigo. E as docstrings foram alteradas para refletir as mudanças.
Adds the spider for the [new system which currently publishes gazettes for Recife (PE)](https://dome.recife.pe.gov.br/dome/).
For this, the old spider had it's name modified to "pe_recife_acervo_2015_a_2020" and the new has the name of "pe_recife", being the main spider now.
The class attributes `start_date` and `end_date` were also added in the old spider. …
> Adiciona raspador para Recife e adapta antigo

- data_collection/gazette/monitors.py
With the increase in the number of spiders sending notification in
Telegram for successful executions is creating too many noise making it
difficult to see the failures.
> Send notification to Telegram only on failures

- data_collection/gazette/spiders/pb_joao_pessoa.py
[João Pessoa](https://www.joaopessoa.pb.gov.br/noticias/prefeitura-de-joao-pessoa-vai-implantar-diario-oficial-eletronico/) changed the system that displays the gazettes. So we need to rewrite the spider to get all gazettes after 28/03/2022.
**AFTER MERGING THIS PR WE NEED TO MANUALLY RUN THE SPIDER TO GET DATA FROM 28/03/2022**
> Update João Pessoa-PB spider after website changed

- data_collection/gazette/spiders/ms_campo_grande.py
This is the start of an attempt into refactoring this spider to accomodate the new website. Although, figuring out how the website generates the urls for the documents was not straightforward and I'll try again later. If anyone wants to address this in the meantime, feel free to take it from here :)
An example of the the frontend version of the website: `https://diogrande.campogrande.ms.gov.br/edicoes/?palavra=&numero=&de=01%2F01%2F1998&ate=19%2F07%2F2021`.
> Fix ms_campo_grande

- data_collection/gazette/spiders/rj_rio_de_janeiro.py
We need to allow to run the spider providing `end_date` attribute, to avoid extra requests for dates that we are not interested. By default end_date is set to the current date if not provided.
>  Update end date parameter to allow filter by period

- data_collection/gazette/spiders/ms_campo_grande.py
After fixing a
[TypeError](https://github.com/okfn-brasil/querido-diario/pull/577) the
spider started to run in infinite loop, as if there is no gazettes
result, te parse metho still try to request the next page result.
Without a limit, the spider would run forever. This PR solves that
problem requesting the pages only one time.
> Fix pagination infinite loop

- data_collection/gazette/spiders/pr_londrina.py
- scripts/enabled_spiders.py
Previous implementation was collecting data from an old (but still
available) website. This old website had gazettes only until mid-2019.
New implementation gets the gazettes before 2019 and the current ones.
> Londrina-PR

- data_collection/gazette/spiders/rj_nova_iguacu.py
If a browser User-Agent is not added to the request, the page was returning a 403 error and nothing are being collected.
> Add user-agent to requests to avoid blocking

- data_collection/gazette/spiders/mt_rondonopolis.py
Spider para raspagem dos diários oficiais de Rondonópolis-MT (resolve #696).
> Add Rondonópolis-MT #696

- .flake8
Mensagem do commit:
Since black is opinionated about some formatting rules, it violates the current W503 rule in flake8
As per https://www.flake8rules.com/rules/W503.html there is a discussion to change the W503 to match the same way black adopts but while this change has not been applied we should ignore the W503 rule for now
Abri esse PR pelo fato de que para os commits de spiders com condições compostas, W503 é acionado como um erro na etapa de análise de flake8, o que é causado devido à formatação aplicada por black.
Talvez não tivesse necessidade de abrir um PR somente com esse commit, mas como …
> Ignore W503 on flake8 due to black and flake8 conflicts

- data_collection/gazette/spiders/ap_santana.py
Adiciona spider para extrair os Diários Oficiais do município de Santana - AP  ( closes #683 )
> Add Santana-AP spider

- data_collection/requirements-dev.txt
- data_collection/requirements.in
- data_collection/requirements.txt
- data_collection/scrapinghub.yml
Como mencionado em #778, reverter #773 e #774 seria importante por enquanto para que o upload de arquivos volte a funcionar.
Este PR realiza essa reversão.
> Reverte dependências dos projetos

- .github/workflows/schedule_spider_by_date.yaml
- scripts/scheduler.py
This command allows us to schedule all enabled spiders after a specific date. This would be useful if we want to run many spiders at the same time, without requiring to schedule wach one individually.
> Create command to schedule all enable spiders with a start date

- data_collection/gazette/spiders/sp_jaboticabal.py
> Add Jaboticabal-SP Spider

- data_collection/gazette/spiders/rj_arraial_do_cabo.py
- scripts/enabled_spiders.py
O código antigo não estava extraindo os diários, fiz algumas alterações e incluí a data de início (resolve https://github.com/okfn-brasil/querido-diario/issues/796).
> Fix Arraial do Cabo-RJ

- data_collection/gazette/spiders/sp_ibitinga.py
- scripts/enabled_spiders.py
resolve #799 
Não marquei o check dos campos pois não entendi (ainda) como conferir.
Percebi também que faltou um arquivo (edição 113, [link](https://www.ibitinga.instarbr.com.br/portal/diario-oficial/ver/115)) pois não tem data registrada no site, logo ele não aparece quando é feito o filtro por data.
> Fix Ibitinga-SP Spider

- data_collection/gazette/monitors.py
Include more information about the failures, so it will be easier to understand what happened to a specific job just looking at the Discord notification message content.
> Add monitor failure description to Discord notification

- .pre-commit-config.yaml
- data_collection/gazette/spiders/df_brasilia.py
Junto ao @giuliocc, percebemos que o raspador de Brasília estava sendo bloqueado por IP. Adicionamos a cidade ao smartproxy da zyte. 
Este PR também corrige versão do isort usada no projeto.
> Corrige df_brasilia

- .github/ISSUE_TEMPLATE/novo_municipio.yaml
- .github/ISSUE_TEMPLATE/novo_sistema_replicavel.yaml
- .github/ISSUE_TEMPLATE/revisao_retroativa.yaml
Este PR propõe um modelo de issue para a adição de novos municípios ao projeto, visando facilitar a triagem e desenvolvimento do novo raspador.
Dessa forma, quando o contribuidor for abrir uma nova issue, verá a seguinte tela:
Clicando em get started será direcionado a um formulário para preencher com informações sobre o município e site de publicação:
-----
Importante destacar que o formulário em si ainda está em beta no GitHub, e que também é possível criar templates em um modelo "livre" como o template de PR. Documentação [aqui](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).
> Sugestão de template para issues de novos municípios

- data_collection/gazette/spiders/pr_maringa.py
- scripts/enabled_spiders.py
PR referente à issue #843 
Código estava com problemas em:
start_date e end_date não funcionavam corretamente.
Falta de "Numero de edição" na coleta dos Diários.
Excessivos requests em alguns Crawls pela falta de filtro nas datas
Em geral o código está funcionando bem. Porém, quando rodei o código algumas vezes sem CACHE previ-o do site, senti que talvez por ele rodar varias paginas de um vez com callbacks, isso dificulte a conexão com o site e atrapalhe o desempenho em alguns momentos.
> [Revisão retroativa] Maringa-PR

- data_collection/gazette/spiders/rn_mossoro.py
- data_collection/gazette/spiders/rn_mossoro_2008_2022.py
Resolves #835 . Código atualizado para também capturar os dados do novo portal.
> Fix rn_mossoro

- data_collection/gazette/spiders/mg_taiobeiras.py
- scripts/enabled_spiders.py
Inclusão de três municípios que utilizam o sistema Instar de gerenciamento de diários oficiais em Minas Gerais, sendo estes, Januária, Onça de Pitangui e Taiobeiras. Em relação ao município de [Onça de Pitangui](www.oncadopitangui.mg.gov.br/), a cidade utiliza dois nomes (Onça de(do) Pitangui), portanto, utilizei somente o nome ao qual consta no IBGE e na aba [Dados do Município](https://www.oncadopitangui.mg.gov.br/portal/servicos/1008/dados-do-municipio/).
> Add Taiobeiras (MG)

- .github/workflows/schedule_spider.yaml
Corrige nome do parâmetro "end date" da action `schedule_spider` que aparece na interface.
> Corrige nome de parâmetro da action schedule_spider

- data_collection/gazette/database/models.py
- data_collection/gazette/pipelines.py
- data_collection/gazette/spiders/pe/recife_2015.py
- data_collection/gazette/spiders/pe/recife_2020.py
- scripts/enabled_spiders.py
Essa é uma alternativa a solução proposta em https://github.com/okfn-brasil/querido-diario/pull/837
Algumas possíveis vantagens:
- Evita alterar o comando `crawl` do Scrapy. Isso reduz o risco de adicionarmos coisas incompatíveis com a `Scrapy Cloud`, plataforme onde estamos executando os raspadores atualmente;
- Manter o comportamento padrão do `scrapy crawl` retira uma barreira para novos desenvolvedores e aquelas com pouca experiência com Scrapy;
- Permite habilitar/desabilitar raspadores existentes alterando o banco de dados (necessário implantar um endpoint na API para gerenciar isso);
- A execução é por spider e não por cidade, já que existem situações onde um spider atende múltiplas cidades;
- A responsabilidade de chamar os spiders certos a partir da data fica totalmente com o …
> Múltiplos raspadores para mesma cidade e múltiplas cidades para mesmo raspador

- data_collection/gazette/spiders/sp_paulinia.py
- scripts/enabled_spiders.py
Adiciona novo spider para Paulínia-SP
resolve #639
> [novo spider] Paulínia-SP

- data_collection/gazette/spiders/es_cariacica.py
- scripts/enabled_spiders.py
Este PR finaliza o trabalho começado por @cecivieira no PR #448. Não consegui reabrir o PR e continuar por lá, por isso submeto um novo.
> [novo spider] Cariacica-ES

- data_collection/gazette/spiders/ba_barreiras.py
- scripts/enabled_spiders.py
- [] Você verificou que não existe nenhum erro nos logs (`log/ERROR` igual a zero).
resolve #862 
Validei os erros. Só não marquei o item na checklist, pois há erros, mas não por conta do raspador. 
Algumas páginas de diários estão vazias, por exemplo: http://www.barreiras.ba.gov.br/diario/pdf/diario924.pdf
> Adiciona raspador para Barreiras-BA

- data_collection/gazette/spiders/se_nossa_senhora_do_socorro.py
- scripts/enabled_spiders.py
- [ X ] Você executou uma extração completa do spider localmente e os dados retornados estavam corretos.
- [ X ] Você executou uma extração por período (`start_date` e `end_date` definidos) ao menos uma vez e os dados retornados estavam corretos.
- [ X ] Você verificou que não existe nenhum erro nos logs (`log/ERROR` igual a zero).
- [ X ] Você definiu o atributo de classe `start_date` no seu spider com a data do Diário Oficial mais antigo disponível na página da cidade.
- [ X ] Você garantiu que todos os campos que poderiam ser extraídos foram extraídos [de acordo com a documentação](https://docs.queridodiario.ok.org.br/pt/latest/escrevendo-um-novo-spider.html#definicao-de-campos).
PR referente à issue [#833](https://github.com/okfn-brasil/querido-diario/issues/833) criação do spider …
> Add Nossa Senhora do Socorro - SE spider

- data_collection/gazette/spiders/base/adminlte.py
- data_collection/gazette/spiders/pa_santana_do_araguaia.py
- data_collection/gazette/spiders/to_gurupi.py
- scripts/enabled_spiders.py
- Adiciona spider base para o AdminLTE (#871 )
- Adiciona spider para Gurupi-TO (base AdminLTE) (#878 )
- Adiciona spider para Santana do Araguaia-PA (base AdminLTE) (#879)
> Adiciona base AdminLTE e suas cidades

- data_collection/gazette/settings.py
Resolve #929 
Atualizando minha venv local com os novos requirements, a execução de Prado-BA - mesmo raspador apontado na issue, coletando apenas desde agosto/23 até hoje, gera os seguintes arquivos: 
[prado_com_erro.csv](https://github.com/okfn-brasil/querido-diario/files/12612259/prado_com_erro.csv) - vazio
[prado_com_erro.txt](https://github.com/okfn-brasil/querido-diario/files/12612261/prado_com_erro.txt)
Ao fazer as atualizações propostas neste PR, temos (para o mesmo período de coleta):
[prado_modificado.csv](https://github.com/okfn-brasil/querido-diario/files/12612271/prado_modificado.csv) - coleta com sucesso
[prado_modificado.txt](https://github.com/okfn-brasil/querido-diario/files/12612273/prado_modificado.txt)
Atualizar a biblioteca deprecada `pkg_resources` foi um dos erros …
> Corrige conflitos de produção (#929)

- data_collection/gazette/spiders/rn/rn_mossoro.py
- data_collection/gazette/spiders/rn/rn_mossoro_2008.py
- data_collection/gazette/spiders/rn/rn_mossoro_2023.py
- scripts/enabled_spiders.py
O raspador pra Mossoró está coletando o HTML da página intermediária do site publicador e não o PDF de fato.
> Ajusta Mossoro-RN

- .github/workflows/periodic_crawl.yaml
Estamos com um problema com a Zyte: os raspadores que duravam cerca de 1 minuto para executar, estão levando de 10 a 30 inesperadamente, fazendo com que a execução completa dos 161 raspadores leve mais de 12 horas. 
Um ticket foi aberto para encaminhar a situação, mas temporariamente, estamos reduzindo a execução de raspadores para uma vez por dia já que uma das ondas não está sendo adequadamente executada pela anterior estar durando muito.
> Configura execução uma vez por dia

- data_collection/gazette/spiders/ba/ba_cristopolis.py
- scripts/enabled_spiders.py
Issue: Adicionar novas cidades de sistemas replicáveis (2/3)
Realizei a adição do spider da cidade de Cristópolis citado na PR1.
> PR1 - Cristópolis BA

- data_collection/gazette/spiders/ms/ms_bela_vista.py
- data_collection/gazette/spiders/ms/ms_costa_rica.py
- data_collection/gazette/spiders/pr/pr_antonio_olinto.py
adiciona raspadores de três cidades (Antônio Olinto PR, Bela Vista MS e Costa Rica MS) da issue #984
> adiciona raspadores de tres cidades pr3 da issue 984

- data_collection/gazette/spiders/sp/sp_lagoinha.py
- data_collection/gazette/spiders/sp/sp_luiziania.py
- data_collection/gazette/spiders/sp/sp_poloni.py
- data_collection/gazette/spiders/sp/sp_santa_maria_da_serra.py
- scripts/enabled_spiders.py
- [Issue 1001](https://github.com/okfn-brasil/querido-diario/issues/1001)
- Task 1
- Cidades adicionadas:
-  Poloni-SP
- Santa Maria da Serra-SP
- Lagoinha-SP
- Luiziânia-SP
> add cidades Instar (Poloni-SP, Santa Maria da Serra-SP, Lagoinha-SP, Luiziânia-SP)

- data_collection/gazette/spiders/sp/sp_joao_ramalho.py
- data_collection/gazette/spiders/sp/sp_mira_estrela.py
- data_collection/gazette/spiders/sp/sp_nova_luzitania.py
- data_collection/gazette/spiders/sp/sp_planalto.py
- data_collection/gazette/spiders/sp/sp_sebastianopolis_do_sul.py
- scripts/enabled_spiders.py
- [Issue 1001](https://github.com/okfn-brasil/querido-diario/issues/1001)
- Task 2
- Cidades adicionadas:
-  Planalto-SP
- João Ramalho-SP
- Sebastianópolis do Sul-SP
- Mira Estrela-SP
- Nova Luzitânia-SP
> add cidades Instar (Planalto-SP, João Ramalho-SP, Sebastianópolis do Sul-SP, Mira Estrela-SP, Nova Luzitânia-SP)

- data_collection/gazette/spiders/sp/sp_aguas_de_sao_pedro.py
- data_collection/gazette/spiders/sp/sp_brejo_alegre.py
- data_collection/gazette/spiders/sp/sp_floreal.py
- data_collection/gazette/spiders/sp/sp_pontes_gestal.py
- data_collection/gazette/spiders/sp/sp_taquaral.py
- scripts/enabled_spiders.py
- [Issue 1001](https://github.com/okfn-brasil/querido-diario/issues/1001)
- Task 3
- Cidades adicionadas:
-  Águas de São Pedro-SP
- Floreal-SP
- Taquaral-SP
- Brejo Alegre-SP
- Pontes Gestal-SP
> add cidades Instar (Águas de São Pedro-SP, Floreal-SP, Taquaral-SP, Brejo Alegre-SP, Pontes Gestal-SP)

- data_collection/gazette/spiders/sp/sp_arapei.py
- data_collection/gazette/spiders/sp/sp_dirce_reis.py
- data_collection/gazette/spiders/sp/sp_nova_castilho.py
- data_collection/gazette/spiders/sp/sp_turiuba.py
- data_collection/gazette/spiders/sp/sp_uniao_paulista.py
- scripts/enabled_spiders.py
- [Issue 1001](https://github.com/okfn-brasil/querido-diario/issues/1001)
- Task 4
- Cidades adicionadas:
-  Arapeí-SP
- Turiúba-SP
- Dirce Reis-SP
- União Paulista-SP
- Nova Castilho-SP
> add cidades Instar (Arapeí-SP, Turiúba-SP, Dirce Reis-SP, União Paulista-SP, Nova Castilho-SP)

- data_collection/gazette/spiders/sc/sc_florianopolis.py
- Spider fufnciona localmente, mas não funciona na Scrapy Cloud. Habilitando o Smart Proxy para evitar problemas de geolocalização
- Ajuste de URL inicial para usar HTTPS ao invẽs de HTTP
- Substituir mẽtodos antigos (extract() e extract_first()) por get() e getall(), considerados o padrão do Scrapy
> Habilita Zyte Smart Proxy em Florianópolis-SC

- data_collection/gazette/monitors.py
- No spider de Maringá-PR, existem 2 requests que sempre são realizados, não importa a quantidade de items, e para cada item, podemos ter até 3 requests (alguns redirecionamentos para obter a URL de download do PDF). No caso de 1 item retornado, a razão request/item estava em 5 (que é a razão considerada aceitável). Porém o monitor estava verificando se o resultado era "menor" que a razão e não "menor e igual". Isso estava gerando muitos falsos positivos.
> Verifica se a razão request/item é menor ou igual ao valor configurado

- data_collection/gazette/resources/territories.csv
Para visualizar as modificações melhor, o arquivo `territories.csv` precisou primeiro ser ordenado (https://github.com/okfn-brasil/querido-diario/pull/1050/commits/49e8bde7f26a8d6cd627498d6a92a3b95f1cb5d0 - neste commit, é possível comparar o antes e o depois e perceber que as 100 últimas linhas não estavam ordenadas). 
Com o arquivo ordenado, passou a ser possível comparar e visualizar as modificações necessárias (https://github.com/okfn-brasil/querido-diario/pull/1050/commits/9c5d5bce7748341721d98b9a35a4e7cafd4378b9).
> Corrige arquivo territories.csv

- data_collection/gazette/resources/territories.csv
- data_collection/gazette/spiders/al/al_associacao_municipios.py
- scripts/enabled_spiders.py
A data inicial de publicação foi descoberta na força bruta, colocando a data inicial em 2009 e tendo o primeiro arquivo baixado apenas em 10/04/2014.
Esqueci de salvar o log, mas executei a raspagem completa localmente algumas vezes sem maiores problemas e tudo foi devidamente processado pelo data-processing local.
Estou adicionando uma entrada no `territories.csv` para a associação. Não necessariamente ficará lá, mas por enquanto é necessário para reproduzir o processamento de dados localmente (a inserção também já foi feita no banco de produção). 
**Não mesclar esse PR antes de …
> Adiciona raspador para AMA (AL)

- data_collection/gazette/spiders/mg/mg_belo_horizonte.py
Issue: https://github.com/okfn-brasil/querido-diario/issues/1054
Foi identificado que adicionaram um parâmetro na chamada que baixa o documento('prefix'), um parâmetro que recebe uma string com a data do dia anterior ao do diário.
Foi realizado o ajusta na url de chamada. 
Rodei localmente e retornaram os documentos dos últimos 15 dias.
> Adiciona o novo 'prefix' parametro a url de download do documento

- data_collection/gazette/database/models.py
Ao adicionar um novo raspador no projeto, a tabela no banco de raspadores não está sendo atualizada automaticamente. Este PR verifica quais raspadores estão no projeto e não estão no banco para adicioná-los pelo menos ao executar um novo raspador (idealmente seria um comando a parte).
> Corrige update de raspadores no banco

- data_collection/gazette/spiders/to/to_sampaio.py
Implementa o spider para a cidade de Sampaio/TO.
Issue: https://github.com/okfn-brasil/querido-diario/issues/1022
> Adiciona spider de TO Sampaio.

- data_collection/gazette/spiders/rj/rj_sao_joao_de_meriti.py
Construção da spider pra São João de Meriti/RJ através do portal https://transparencia.meriti.rj.gov.br/. 
Consulta mês a mês através do subdomínio _/diario_oficial_get.php_ e desconsidera os itens com código de anexo igual a 1. 
Download delay de 1.5 segundos para evitar o recebimento de error de servidor 500.
Estrutura de código similar ao encontrado para a cidade de Belford Roxo/RJ. 
Resolve #961
> São João de Meriti/RJ

- data_collection/gazette/mapeadores/mapeadoratende.py
Implementa a sugestão apresentada em [919 (comment)](https://github.com/okfn-brasil/querido-diario/issues/919/#issuecomment-1821736963)
> NOTA: Link para a página de cada município: `https://{city}.atende.net` 
**Por não ser um domínio governamental** (diferente de `.{uf}.gov.br`), apresenta o problema conhecido: `encontra URLs de interesse, mas vincula na cidade errada`. 
1. Ao retirar o `http` dos protocolos de mapeamento e **não** tentar mapear o link 'base' para a página de cada município `{protocol}://{city}.atende.net`, o **tempo para mapear 500 cidades** (tempo entre backups parciais) foi reduzido de 2h40min para 25 minutos.
---
abaixo. **NÃO ABRA** um novo Pull Request …
> Adiciona mapeador ATENDE

- data_collection/gazette/spiders/al/al_igaci.py
- data_collection/gazette/spiders/ba/ba_correntina.py
- data_collection/gazette/spiders/ba/ba_jaborandi.py
- data_collection/gazette/spiders/ba/ba_jeremoabo.py
- data_collection/gazette/spiders/ba/ba_lauro_de_freitas.py
- data_collection/gazette/spiders/ba/ba_luis_eduardo_magalhaes.py
- data_collection/gazette/spiders/ba/ba_maragogipe.py
- data_collection/gazette/spiders/ba/ba_riachao_das_neves.py
- data_collection/gazette/spiders/base/sai.py
- data_collection/gazette/spiders/se/se_estancia.py
Implementação do raspador para sites produzidos pelo SAI, presentes na Issue #907
> Raspadores de SAI - Eatapa 1

- data_collection/gazette/spiders/ba/ba_campo_alegre_de_lourdes.py
- Add spider para a cidade Campo Alegre de Lourdes - BA usando o spider base DoemGazetteSpider
**Execução completa** 
- Log: [full_ba_campo_alegre_de_lourdes.txt](https://github.com/okfn-brasil/querido-diario/files/14673129/full_ba_campo_alegre_de_lourdes.txt)
- Output: [full_ba_campo_alegre_de_lourdes.csv](https://github.com/okfn-brasil/querido-diario/files/14673128/full_ba_campo_alegre_de_lourdes.csv)
**Execução por período** 
start_date: 2020-11-01
end_date: 2020-12-15
- Log: [log-from-2020-11-01-to-2020-12-15-ba_campo_alegre_de_lourdes.txt](https://github.com/okfn-brasil/querido-diario/files/1467 …
> [new spider] Campo Alegre de Lourdes - BA

- data_collection/gazette/spiders/base/dionet.py
- data_collection/gazette/spiders/es/es_associacao_municipios.py
- data_collection/gazette/spiders/es/es_serra.py
- data_collection/gazette/spiders/ms/ms_corumba.py
- data_collection/gazette/spiders/ms_corumba.py
- data_collection/gazette/spiders/rj/rj_rio_de_janeiro.py
- data_collection/gazette/spiders/ro/ro_jaru.py
- data_collection/gazette/spiders/sp/sp_sao_jose_dos_campos.py
PR com proposta de resolução parcial do item #724, refatorando o código comum a dois spiders já em produção:
- `rj_rio_de_janeiro`
- [log](https://gist.github.com/ayharano/47f439ab3351cd898de61ea43f0f93d5/raw/f09f7785db0291c0b36af2434078dbb8adb8d3fc/rj_rio_de_janieiro.log)
- [md5sum dos arquivos](https://gist.github.com/ayharano/47f439ab3351cd898de61ea43f0f93d5/raw/f09f7785db0291c0b36af2434078dbb8adb8d3fc/rj_rio_de_janeiro.md5sum.txt)
- `es_serra`
- [log](https://gist.githubusercontent.com/ayharano/47f439ab3351cd898de61ea43f0f93d5/raw/f09f7785db0291c0b36af2434078dbb8adb8d3fc/es_serra.log)
- [md5sum …
> Refatoração para o uso de um spider base para DIONET

- data_collection/gazette/spiders/mg/mg_uberlandia.py
Segunda, o raspador para Uberlândia-MG em produção deu erros 403 (sendo que no teste local não deu esse problema - logs adicionados em #638) e o proxy foi adicionado por conta disso (#1128). O que não adiantou. Depois foi percebido que os testes locais também não funcionavam mais (talvez por ter sido diagnosticada as dinâmicas de raspagem). Fez-se necessário o uso de user-agent (#1129) e não havia mais evidência que o problema era de proxy, por isso o proxy foi retirado. 
Agora, está fazendo apenas a primeira requisição e não permitindo ela, então tentamos o proxy novamente.
> Adiciona proxy em mg_uberlandia.py

- data_collection/gazette/spiders/sp/sp_cacapava.py
Os boletins podem ser consultados em intervalos de datas através do site https://cacapava.sp.gov.br/diario-oficial.
[log_sp_cacapava.txt](https://github.com/okfn-brasil/querido-diario/files/14151676/log_sp_cacapava.txt)
[log_sp_cacapava.csv](https://github.com/okfn-brasil/querido-diario/files/14151678/log_sp_cacapava.csv)
resolve #1071
> new spider Caçapava/SP

- data_collection/gazette/spiders/base/dosp.py
- data_collection/gazette/spiders/mg/mg_uberaba_2003.py
- data_collection/gazette/spiders/mg/mg_uberaba_2021.py
Mudança para  o sistema replicável DOSP.
- Redução de requisições para "https://dosp.com.br/api/"  (4 requisições a menos por mês em media)
- Um pouco mais de estabilidade em longas extrações
- Um pouco mais de simplificação de código 
**A mudança custa um tempo maior em extrações mais longas**
> Mundança Sistema Replicavel DOSP

- data_collection/gazette/spiders/base/adiarios_v2.py
- data_collection/gazette/spiders/rj/rj_casimiro_de_abreu.py
- data_collection/gazette/spiders/rj/rj_cordeiro.py
Adiciona a base para adiarios com um segundo layout de pagina (o primeiro foi adicionado por #885) com os dois únicos casos conhecidos até o momento
> Adiciona spider para adiarios com outro layout de página

- data_collection/gazette/pipelines.py
- data_collection/requirements-dev.txt
- data_collection/requirements.in
- data_collection/requirements.txt
Melhorias em https://github.com/okfn-brasil/querido-diario/pull/1045
Quando a extensão do arquivo não é informada no nome dele, tentamos
identificar ela através dos headers do response ou através de seu
conteúdo. Porém devido a maneira como o Scrapy funciona, isso vai fazer
com que o arquivo seja baixado novamente em novas execuções do spider.
Para resolver esse problema seria necessários muitas mudanças na
estrutura do Scrapy (incluindo a criação de novos FileStorage, o que
tornaria o projeto mais complexo, com um ganho de performance
irrelevante.
Com esse modificação, identificamos a extensão, e se ela não vier por
padrão, o arquivo será baixado novamente toda vez que reexecutarmos o
spider (o que nunca acontece em produção para a data específica)
> Simplifica definição de extensão de arquivo baixado

- data_collection/gazette/spiders/ba/ba_abare.py
- data_collection/gazette/spiders/ba/ba_adustina.py
- data_collection/gazette/spiders/ba/ba_almadina.py
- data_collection/gazette/spiders/ba/ba_anage.py
- data_collection/gazette/spiders/ba/ba_andorinha.py
Os logs de Andorinha, Almadina, Andustina e Abaré tem a contagem de 1 erro.
Terceiro PR com os primeiros 5 municípios da issue #1115. O primeiro PR foi #1134, então #1135 e agora os arquivos estão finalmente corretos.
Arquivos de csv e log gerados:
- última edição 
[log_ba_abare_last.log](https://github.com/okfn-brasil/querido-diario/files/15123713/log_ba_abare_last.log)
[log_ba_adustina_last.log](https://github.com/okfn-brasil/querido-diario/files/15123714/log_ba_adustina_last.log)
[log_ba_almadina_last.log](https://github.com/okfn-brasil/querido-diario/files/15123715/log_ba_almadina_last.log)
[log_ba_anage_last.log](https://github.com/okfn-brasil/querido-diario/files/15123716/log_ba_anage_last.log) …
> Adiciona spiders para Abaré, Adustina, Almadina, Anagé e Andorinha

- data_collection/gazette/spiders/rs/rs_candelaria.py
- data_collection/gazette/spiders/rs/rs_horizontina.py
- data_collection/gazette/spiders/rs/rs_santa_rosa.py
Para padronizar o nome das bases, nos casos em que há um segundo layout, o arquivo `atende_layoutdois.py` foi renomeado para `atende_v2.py`, assim como `adiarios_v1.py` e `adiarios_v2.py` 
A modificação foi feita em https://github.com/okfn-brasil/querido-diario/pull/1157/commits/ae8ce8e91d89a888c16cf7b21c66ddc1714fe948, porém ficou faltando refletir o ajuste em outros 3 raspadores replicados de `atende_v2`. Esta PR os corrigem.
> Atualiza import em 3 arquivos

- data_collection/gazette/spiders/base/instar.py
Alguns raspadores que usam a classe base Instar começaram a enviar muita requisição, em produção, levando horas para coletar apenas uma edição. 
Logs da Zyte com os problemas:
[log_mg_carmo_da_cachoeira_342.txt](https://github.com/user-attachments/files/15809464/log_mg_carmo_da_cachoeira_342.txt)
[log_mg_candeias_351.txt](https://github.com/user-attachments/files/15809466/log_mg_candeias_351.txt)
[log_mg_campo_belo_851.txt](https://github.com/user-attachments/files/15809467/log_mg_campo_belo_851.txt)
[log_mg_contagem_851.txt](https://github.com/user-attachments/files/15809463/log_mg_contagem_851.txt)
O motivo é que o padrão da URL mudou (deixou de terminar com `/0/0/0` e passou a terminar com `/0/0/` ) e por isso o filtro por data não estava mais funcionando. A PR atualiza a spider base. …
> Atualiza formato de url para base Instar

- data_collection/gazette/spiders/mg/mg_carmo_do_rio_claro.py
- data_collection/gazette/spiders/mg/mg_juatuba.py
- data_collection/gazette/spiders/mg/mg_onca_do_pitangui.py
Adicionando vários spiders para o estado de Minas Gerais(MG) - **Barbacena** | **Carmo do Rio Claro** | **Onça do Pitangui** | **Juatuba**
---
**Barbacena, MG: 3105608**
- https://www1.barbacena.mg.gov.br/portal/diario-oficial
- https://cidades.ibge.gov.br/brasil/mg/barbacena/panorama
**Carmo do Rio Claro, MG: 3114402**
- https://www.carmodorioclaro.mg.gov.br/portal/diario-oficial
- https://cidades.ibge.gov.br/brasil/mg/carmo-do-rio-claro/panorama
**Onça do Pitangui, MG: 3151404**
- https://www.oncadopitangui.mg.gov.br/portal/diario-oficial
- https://cidades.ibge.gov.br/brasil/mg/pitangui/panorama
**Juatuba, MG: 3136652**
- https://www.juatuba.mg.gov.br/portal/diario-oficial
- https://cidades.ibge.gov.br/brasil/mg/juatuba/panorama
> Adiciona vários spider de MG - Barbacena | Carmo do Rio Claro | Onça do Pitangui | Juatuba

- data_collection/gazette/spiders/rn/rn_pau_dos_ferros_2017.py
- data_collection/gazette/spiders/rn/rn_pau_dos_ferros_2022.py
- data_collection/gazette/spiders/sp/sp_paulinia.py
resolve item 3 de #1156
Pau dos Ferros-RN é um município cujo código não revisado já existia no repositório (#1162), e que migrou para usar um sistema replicável. 
Paulínia-SP já tinha código integrado e em produção que parou de funcionar por ter migrado para um sistema replicável também. A migração nesse caso mantém o `start_date` igual, parecendo não haver perda de série histórica na transição. 
Esta PR endereça ambos casos.  
Pau dos Ferros - RN
[rn_pau_dos_ferros_2022-intervalo.log](https://github.com/user-attachments/files/15810810/rn_pau_dos_ferros_2022-intervalo.log) | [rn_pau_dos_ferros_2022-intervalo.csv](https://github.com/user-attachments/files/15810811/rn_pau_dos_ferros_2022-intervalo.csv)
[rn_pau_dos_ferros_2022-completa.csv](https://github.com/user-attachments/files/15810809/ …
> Atualiza raspadores para Pau dos Ferros-RN e Paulínia-SP

- data_collection/gazette/spiders/base/doem.py
A coleta diária não estava cumprindo seu propósito - nem sempre coletando diários - pois o filtro por data não funcionava corretamente. 
todas as coletas foram testadas com o atributo `-a start_date=2024-06-14` no mesmo dia. 
[ba_inhambupe-ultimo-dia.log](https://github.com/user-attachments/files/15844871/ba_inhambupe-ultimo-dia.log)
[ba_inhambupe-ultimo-dia.csv](https://github.com/user-attachments/files/15844872/ba_inhambupe-ultimo-dia.csv)
[ba_ipiau-ultimo-dia.log](https://github.com/user-attachments/files/15844873/ba_ipiau-ultimo-dia.log)
[ba_ipiau-ultimo-dia.csv](https://github.com/user-attachments/files/15844874/ba_ipiau-ultimo-dia.csv)
[ba_laje-ultimo-dia.log](https://github.com/user-attachments/files/15844875/ba_laje-ultimo-dia.log) …
> Corrige filtro por data de DOEM

- data_collection/gazette/spiders/sp/sp_sumare.py
O site de Sumaré-SP aparentemente mudou, fazendo o raspador dar o seguinte erro em produção: 
Esta PR atualiza o raspador. 
[sp_sumare_periodo.log](https://github.com/user-attachments/files/15844901/sp_sumare_periodo.log)
[sp_sumare_periodo.csv](https://github.com/user-attachments/files/15844902/sp_sumare_periodo.csv)
[sp_sumare.log](https://github.com/user-attachments/files/15845031/sp_sumare.log)
[sp_sumare.csv](https://github.com/user-attachments/files/15845030/sp_sumare.csv)
> Atualiza raspador para Sumaré-SP

- data_collection/gazette/spiders/ba/ba_santa_luzia_2021.py
- data_collection/gazette/spiders/ba/ba_santa_luzia_2024.py
- data_collection/gazette/spiders/sp/sp_dirce_reis.py
- Santa Luzia-BA 
Dando erro em produção desde 2024-01-29, pois o município mudou de DOEM para SAI.
[ba_santa_luzia_2024-ultimo-dia.log](https://github.com/user-attachments/files/15904920/ba_santa_luzia_2024-ultimo-dia.log) | [ba_santa_luzia_2024-ultimo-dia.csv](https://github.com/user-attachments/files/15904921/ba_santa_luzia_2024-ultimo-dia.csv)
[ba_santa_luzia_2024-intervalo.log](https://github.com/user-attachments/files/15904950/ba_santa_luzia_2024-intervalo.log) | [ba_santa_luzia_2024-intervalo.csv](https://github.com/user-attachments/files/15904951/ba_santa_luzia_2024-interv …
> Atualiza Santa Luzia-BA e Dirce Reis-SP

- data_collection/gazette/spiders/base/adiarios_v1.py
Resolve a issue #1187. Atualizar o código de [adiarios_v1.py](https://github.com/okfn-brasil/querido-diario/blob/main/data_collection/gazette/spiders/base/adiarios_v1.py) para que o fluxo de coleta dos metadados.
Classe base Adiarios V1:
- `edition_number` com valor padrão como string vazia;
- `is_extra_edition` verificada no título e também no texto.
Foram feitas as coletas para os municípios com problemas encontrados na Validação #1185:
- pb_jacarau
- pb_marizopolis
- pb_piloezinhos
- pb_sertaozinho
> :white_check_mark: Depois da correção esses municípios passaram sem error.
[coleta_ultima_edicao_pb_sertaozinho.csv](https://github.com/user-attachments/files/16194261/coleta_ultima_edicao_pb_sertaozinho.csv)
[coleta_ultima_edicao_pb_sertaozinho.log](https://github.com/user-attachments/file …
> Ajustar regex de coleta de metadado #1187

- data_collection/gazette/spiders/pb/pb_jacarau.py
- data_collection/gazette/spiders/pb/pb_jerico.py
- data_collection/gazette/spiders/pb/pb_marizopolis.py
- data_collection/gazette/spiders/pb/pb_piloezinhos.py
- data_collection/gazette/spiders/pb/pb_riachao.py
- data_collection/gazette/spiders/pb/pb_sao_jose_dos_ramos.py
- data_collection/gazette/spiders/pb/pb_serraria.py
- data_collection/gazette/spiders/pb/pb_sertaozinho.py
- data_collection/gazette/spiders/pb/pb_tacima.py
Adiciona 10 raspadores da lista de #1082 
Testes e verificações serão realizadas por @rochamatcomp
> Adiciona novos 10 raspadores da Paraíba

- data_collection/gazette/spiders/base/adiarios_v2.py
- data_collection/gazette/spiders/rj/rj_armacao_dos_buzios.py
- data_collection/gazette/spiders/rj/rj_iguaba_grande.py
- data_collection/gazette/spiders/rj/rj_quissama.py
- data_collection/gazette/spiders/rj/rj_sao_jose_do_vale_do_rio_preto.py
Adiciona 3 novos municípios de adiarios (#1082) e 1 de dosp (#1087)  
- São José do Vale do Rio - RJ
[ultima-edicao_rj_sao_jose_do_vale_do_rio.csv](https://github.com/user-attachments/files/16446216/ultima-edicao_rj_sao_jose_do_vale_do_rio.csv) | [ultima-edicao_rj_sao_jose_do_vale_do_rio.log](https://github.com/user-attachments/files/16446214/ultima-edicao_rj_sao_jose_do_vale_do_rio.log)
[intervalo_rj_sao_jose_do_vale_do_rio.csv](https://github.com/user-attachments/files/16446249/intervalo_rj_sao_jose_do_vale_do_rio.csv) | …
> Adiciona 4 novos municípios do Rio de Janeiro

- data_collection/gazette/spiders/base/aplus.py
- data_collection/gazette/spiders/ma/ma_caxias_2017.py
- data_collection/gazette/spiders/ma/ma_caxias_2021.py
Caxias-MA estava quebrando em produção desde Junho/2024. O município migrou a publicação para outro caminho, usando o padrão aplus já integrado ao projeto. Esta PR adiciona o novo spider e atualiza o anterior.
[completa_ma_caxias_2021.csv](https://github.com/user-attachments/files/16475448/completa_ma_caxias_2021.csv) | [completa_ma_caxias_2021.log](https://github.com/user-attachments/files/16475447/completa_ma_caxias_2021.log)
[intervalo_ma_caxias_2021.log](https://github.com/user-attachments/files/16475449/intervalo_ma_caxias_2021.log) | …
> Adiciona novo spider para Caxias-MA e atualiza o anterior

- data_collection/gazette/spiders/ba/ba_barreiras.py
O raspador para Barreiras-BA estava sem coletar diários desde 2024-07-04. O motivo foi que as URLs pros diários passaram a ser cadastradas no site no formato `<a href="//www.barreiras.ba.gov.br/diario/pdf/2024/diario4217.pdf" ... ` começando com `//` e sem o `http`/`https`. Esta PR adiciona um ajuste para tratar a string da URL.
Foi verificada uma coleta de intervalo (2024-06-01 to 2024-08-02) que contém o intervalo ausente, mas agora obtendo os diários.
[intervalo_ba_barreiras.log](https://github.com/user-attachments/files/16475916/intervalo_ba_barreiras.log)
[intervalo_ba_barreiras.csv](https://github.com/user-attachments/files/16475917/intervalo_ba_barreiras.csv)
> Atualiza ba_barreiras para voltar a coletar diários

- data_collection/gazette/spiders/sp/sp_botucatu.py
Botucatu-SP migrou o site publicador e esta PR atualiza o raspador para coletar o novo site
[intervalo_sp_botucatu.log](https://github.com/user-attachments/files/16482564/intervalo_sp_botucatu.log)
[intervalo_sp_botucatu.csv](https://github.com/user-attachments/files/16482565/intervalo_sp_botucatu.csv)
[ultima-edicao_sp_botucatu.log](https://github.com/user-attachments/files/16482566/ultima-edicao_sp_botucatu.log)
[ultima-edicao_sp_botucatu.csv](https://github.com/user-attachments/files/16482567/ultima-edicao_sp_botucatu.csv)
> Atualiza spider para Botucatu-SP

- data_collection/gazette/spiders/base/modernizacao.py
- data_collection/gazette/spiders/rj/rj_belford_roxo.py
- data_collection/gazette/spiders/rj/rj_mesquita.py
- data_collection/gazette/spiders/rj/rj_miguel_pereira.py
- data_collection/gazette/spiders/rj/rj_quatis.py
- data_collection/gazette/spiders/rj/rj_queimados.py
- data_collection/gazette/spiders/rj/rj_sao_joao_de_meriti.py
- data_collection/gazette/spiders/rj/rj_sao_pedro_da_aldeia.py
**Foi necessário incluir DOWNLOAD_DELAY para alguns municípios para reduzir a quantidade de "retry/reason_count/500 Internal Server Error", que ocasionava erros para baixar alguns itens.**
[LOG - 1221.zip](https://github.com/user-attachments/files/16442279/LOG.-.1221.zip)
#1221 Cria base para o sistema modernização. 
- Adiciona BaseModernizacaoSpider;
- Adiciona 4 novos spiders: rj_miguel_pereira; rj_quatis; rj_queimados e rj_sao_pedro_da_aldeia;
- Atualiza 2 spiders de municípios que utilizam o mesmo sistema: rj_belford_roxo; rj_sao_joao_de_meriti; e
- Atualiza a URL_BASE de …
> #1221 Adiciona base para o sistema modernizacao

- data_collection/gazette/spiders/base/barcodigital.py
- data_collection/gazette/spiders/to/to_lagoa_de_tocantins.py
- data_collection/gazette/spiders/to/to_recursolandia.py
PR feito em colaboração com @adellylima, @r-lelis, @heitorado, @cjasm, @cacoze, @yamawakimiho 
- Issue
- BaseSpider: https://github.com/okfn-brasil/querido-diario/issues/1016
- Cria **BarcoDigital** base spider
- Adiciona Spider da Cidade **Lagoa do Tocatins - TO** 
- Adiciona Spider da Cidade **Recursolândia - TO** 
**Erro na carga completa da cidade Recursolândia**
A Edição 40 do diário oficial não encontra-se disponível no site. Ela foi publicada em 08-06-2020.
**Nome do arquivo:** Edicao-n-040-de-08-06-2020.pdf 
**Link do aquivo pdf:** …
> Add new spider BarcoDigital

- data_collection/gazette/spiders/rj/rj_saquarema.py
[ultima.log](https://github.com/user-attachments/files/16570072/ultima.log)
[intervalo.csv](https://github.com/user-attachments/files/16570075/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/16570076/intervalo.log)
[completa.csv](https://github.com/user-attachments/files/16570078/completa.csv)
[completa.log](https://github.com/user-attachments/files/16570079/completa.log)
Cria spider para Saquarema/RJ, conforme a issue #1212
> Novo spider Saquarema/RJ

- data_collection/gazette/spiders/to/to_sampaio.py
Raspador dando erro em produção, mas funcionando normalmente local 
[to_sampaio.log](https://github.com/user-attachments/files/16880626/to_sampaio.log)
> Habilita proxy para spider to_sampaio

- data_collection/gazette/spiders/rj/rj_angra_dos_reis.py
[ultima.log](https://github.com/user-attachments/files/16570770/ultima.log)
[intervalo.csv](https://github.com/user-attachments/files/16570771/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/16570772/intervalo.log)
[completa.csv](https://github.com/user-attachments/files/16570774/completa.csv)
[completa.log](https://github.com/user-attachments/files/16570775/completa.log)
Cria spider para Angra dos Reis/RJ, conforme issue #1191
> Novo Spider - Angra dos Reis/RJ

- data_collection/gazette/spiders/base/instar.py
- data_collection/gazette/spiders/rj/rj_cabo_frio.py
[intervalo.csv](https://github.com/user-attachments/files/17015014/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/17015016/intervalo.log)
[rj_cabo_frio_completa.csv](https://github.com/user-attachments/files/17015017/rj_cabo_frio_completa.csv)
[rj_cabo_frio_completa.log](https://github.com/user-attachments/files/17015018/rj_cabo_frio_completa.log)
[ultima.csv](https://github.com/user-attachments/files/17015019/ultima.csv)
[ultima.log](https://github.com/user-attachments/files/17015020/ultima.log)
resolve #1267 
Cria spider para Cabo Frio, usando base …
> Cria spider para Cabo Frio / RJ

- data_collection/gazette/spiders/base/adminlte.py
Revisa raspador base AdminLTE.
Coisa simples: só permite protocolo de transferência seguro (https). `url` da base atualizada. Funcionando com todas as cidades.
Issue: #1171
[to_gurupi_intervalo.csv](https://github.com/user-attachments/files/17000348/to_gurupi_intervalo.csv)
[to_gurupi_completa.csv](https://github.com/user-attachments/files/17000349/to_gurupi_completa.csv)
[pa_santana_do_araguaia_intervalo.csv](https://github.com/user-attachments/files/17000350/pa_santana_do_araguaia_intervalo.csv)
[pa_santana_do_araguaia_completa.csv](https://github.com/user-attachments/files/1700 …
> [Manutenção] Classe base AdminLTE

- data_collection/gazette/spiders/ba/ba_itatim.py
Adicionando o município de Itatim-BA (um capricho pessoal antes das eleições)
> feat: implementação do município de itatim

- data_collection/gazette/spiders/pr/pr_apucarana.py
- data_collection/gazette/spiders/pr/pr_campo_largo.py
- data_collection/gazette/spiders/pr/pr_campo_mourao.py
- data_collection/gazette/spiders/pr/pr_castro.py
- data_collection/gazette/spiders/pr/pr_corbelia.py
- data_collection/gazette/spiders/pr/pr_guaraniacu.py
- data_collection/gazette/spiders/pr/pr_mambore.py
- data_collection/gazette/spiders/pr/pr_ouro_verde_do_oeste.py
<Descreva o seu Pull Request informando a issue (caso exista) que está sendo solucionada ou uma descrição do código apresentado>
> Adiciona novos 10 raspadores do Paraná

- data_collection/gazette/spiders/rj/rj_marica.py
[completa.csv](https://github.com/user-attachments/files/17195523/completa.csv)
[completa.log](https://github.com/user-attachments/files/17195525/completa.log)
[intervalo.csv](https://github.com/user-attachments/files/17195526/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/17195528/intervalo.log)
[ultima.csv](https://github.com/user-attachments/files/17195529/ultima.csv)
[ultima.log](https://github.com/user-attachments/files/17195530/ultima.log)
resolve #1201 
Cria Spider para Maricá já implementado as sugestões da PR #1252 
Um novo PR foi necessário …
> Cria spider para Maricá RJ

- data_collection/gazette/resources/territories.csv
- data_collection/gazette/spiders/go/go_associacao_municipios.py
- data_collection/gazette/spiders/go/go_associacao_municipios_fgm.py
- data_collection/gazette/spiders/go/go_federacao_municipios.py
- data_collection/gazette/spiders/pa/pa_federacao_municipios.py
- data_collection/gazette/spiders/pb/pb_federacao_municipios.py
- data_collection/gazette/spiders/rn/rn_federacao_municipios.py
Esta PR... 
- atualiza territories.csv com as IDs para Agregações usados pelos raspadores
- renomeia alguns arquivos para desfazer ambiguidade entre "associação" e "federação" de municípios, visto que um estado pode ter ambos
- No caso dos dois arquivos para Goiás, uma associação e uma federação, troca o Territory_ID de um deles para um novo valor visto que era o mesmo duas vezes
> Realiza atualizações relacionadas aos casos de agregações

- data_collection/gazette/spiders/mg/mg_carmo_do_rio_claro.py
- data_collection/gazette/spiders/mg/mg_juatuba.py
Devido a um erro no rebase da PR #1281 -- onde foi solicitado que o código de raspadores já existentes no repositório fossem retirado **da PR**, acabei retirando do repositório por engano --, esta PR faz um cherry-pick no commit que havia originalmente adicionado os raspadores no repositório, reintegrando-os.
> Re-adiciona 2 raspadores de Minas Gerais

- data_collection/gazette/spiders/al/al_maragogi.py
Reimplementação do raspador do município de Maragogi AL , anteriormente citado nesta issue https://github.com/okfn-brasil/querido-diario/issues/1176 e feito parcialmente nesta PR https://github.com/okfn-brasil/querido-diario/pull/1186, porém o mesmo ficou muito tempo esperando retorno do desenvolvedor, visto que houve mudanças drásticas no site dos diários oficiais em questão, decidi abrir esta nova PR para facilitar o fluxo de revisão
- Logs e outputs de uma extração completa:
[output-all.log](https://github.com/user-attachments/files/17197804/output-all.log)
[output-all.csv](https://github.com/user-attachments/files/17197805/output-all.csv)
- Logs e outputs de uma extração com data aleatória (2024-05-10 até 2024-08-23): …
> Al maragogi

- .github/pull_request_template.md
Os links estavam quebrados e não estavam apontando para o local correto na documentação.
> corrige links quebrados no formulário de PR's

- data_collection/gazette/spiders/to/to_caseara.py
- data_collection/gazette/spiders/to/to_itapiratins.py
- data_collection/gazette/spiders/to/to_itapiratins_2017.py
- data_collection/gazette/spiders/to/to_miracema.py
- data_collection/gazette/spiders/to/to_muricilandia.py
- data_collection/gazette/spiders/to/to_santa_fe_do_araguaia.py
- data_collection/gazette/spiders/to/to_talisma.py
Adiciona 6 raspadores de municípios replicados a partir do padrão BaseDOBR mencionado na https://github.com/okfn-brasil/querido-diario/issues/1090#issuecomment-2372690577:
Code | City 
-- | -- 
1703909 | Caseara	-	TO 
1710904 | Itapiratins	-	TO 
1713205 | Miracema	-	TO | 
1713957 | Muricilândia	-	TO | 
1718865 | Santa Fé do Araguaia	-	TO | 
1720978 | Talismã	-	TO |
> Adiciona 6 raspadores de #1090

- .github/workflows/daily_crawl.yaml
- .github/workflows/deploy.yml
- .github/workflows/monthly_crawl.yaml
- .github/workflows/schedule_spider.yaml
- .github/workflows/schedule_spider_by_date.yaml
- .github/workflows/schedule_spider_yearly.yaml
- .github/workflows/tests.yml
- .github/workflows/update_spider_status.yaml
Temos uma limitação do uso da Zyte que é o tempo de coleta do raspador restrito à 1h. Raspadores que levam mais do que isso para fazer a coleta completa, precisam ser fatiados manualmente. 
Por isso, esta PR adiciona um novo workflow de raspagem que fatia a coleta completa por ano, por padrão. 
Também renomeia os outros workflows pois foi uma recomendação da ferramenta [act](https://github.com/nektos/act) - para testar github actions - que a identificação dos jobs sejam univocas
> Adiciona novo workflow de raspagem fatiada anualmente

- data_collection/gazette/spiders/pr/pr_sao_joao_do_triunfo.py
[LAST.txt](https://github.com/user-attachments/files/18085996/LAST.txt)
[INTERVAL_LOG.txt](https://github.com/user-attachments/files/18085792/INTERVAL_LOG.txt)
[INTERVAL_LOG.csv](https://github.com/user-attachments/files/18085984/INTERVAL_LOG.csv)
[COMPLETE_LOG.txt](https://github.com/user-attachments/files/18086008/COMPLETE_LOG.txt)
[COMPLETE_LOG.csv](https://github.com/user-attachments/files/18086011/COMPLETE_LOG.csv)
Raspador para a cidade de São João do Triunfo - PR
> Spyder sao joao do triunfo

- data_collection/gazette/spiders/ma/ma_anajatuba.py
- data_collection/gazette/spiders/ma/ma_bom_jardim.py
- data_collection/gazette/spiders/ma/ma_bom_lugar.py
Adiciona 10 raspadores da lista de #1082
> Adiciona novos 3 raspadores do Maranhão

- data_collection/gazette/spiders/sp/sp_campinas.py
O site não mudou, mas o raspador estava sem coletar edições desde 6/dez/24, sem fazer nenhuma requisição em produção.
> Habilita smartproxy para Campinas-SP

- data_collection/gazette/spiders/base/modernizacao.py
- data_collection/gazette/spiders/rj/rj_belford_roxo.py
O serviço modernização parece permitir que as prefeituras escolham entre algumas opções de seção do site onde adicionar os diários oficiais
No geral, os municipios dos raspadores derivados de BaseModernizacao que estão no repositório usam a aba "Diário Oficial do Município" para publicar diários - é o caso de Mesquita-RJ: https://transparencia.mesquita.rj.gov.br/
Já Belford Roxo-RJ passou a usar a seção "Diário Oficial Grande Circulação" - https://transparencia.prefeituradebelfordroxo.rj.gov.br/
Como layout da página e os campos de acesso oferecidos continuam iguais (ou seja, o parse() segue relevante para ambos os casos) a base foi atualizada para permitir acesso ao outro endpoint, não demandando uma base nova e independente apenas para Belford Roxo-RJ 
Esta PR resolve o problema de …
> Atualiza base modernização para dar manutenção no raspador de Belford Roxo-RJ

- data_collection/gazette/spiders/df/df_brasilia.py
##
Tenho uma app que fiz em 2022 antes de conhecer o QD pra coletar a edições diárias do [DODF](https://www.dodf.df.gov.br/) em versão JSON e monitorar as publicações do meu interesse a partir de palavras chaves. Há alguns meses atrás recebi notificações do GitHub Actions de que as requisições app estavam falhando, mas como estava sem tempo naquele momento deixei pra verificar depois. Retomando agora, identifiquei qual era o problema no meu app e percebi que poderia utilizar isso pra contribuir com o QD também.
Em Outubro/2024 o site do DODF foi atualizado pra nova versão, com a …
> Hotfix: Adapting Spider [df_brasilia] to Changes in the DODF Website/API

- data_collection/gazette/spiders/sc/sc_florianopolis_2009.py
- data_collection/gazette/spiders/sc/sc_florianopolis_2024.py
[sc_florianopolis_2024_ultima.log](https://github.com/user-attachments/files/18383905/sc_florianopolis_2024_ultima.log) | [sc_florianopolis_2024_ultima.csv](https://github.com/user-attachments/files/18383906/sc_florianopolis_2024_ultima.csv)
[sc_florianopolis_2024_periodo_1mes.log](https://github.com/user-attachments/files/18383907/sc_florianopolis_2024_periodo_1mes.log) | [sc_florianopolis_2024_periodo_1mes.csv](https://github.com/user-attachments/files/18383908/sc_florianopolis_2024_periodo_1mes.csv)
[sc_florianopolis_2024_periodo_1semana.log](https://github.com/user-attachments …
> Adiciona novo raspador para Florianópolis-SC e atualiza antigo

- data_collection/gazette/spiders/base/aratext.py
- data_collection/gazette/spiders/ma/ma_centro_do_guilherme.py
- data_collection/gazette/spiders/ma/ma_maranhaozinho.py
- data_collection/gazette/spiders/sc/sc_florianopolis_2024.py
[ma_centro_do_guilherme_ultima.log](https://github.com/user-attachments/files/18386717/ma_centro_do_guilherme_ultima.log) | [ma_centro_do_guilherme_ultima.csv](https://github.com/user-attachments/files/18386718/ma_centro_do_guilherme_ultima.csv)
[ma_maranhaozinho_ultima.log](https://github.com/user-attachments/files/18386719/ma_maranhaozinho_ultima.log) | [ma_maranhaozinho_ultima.csv](https://github.com/user-attachments/files/18386720/ma_maranhaozinho_ultima.csv)
[ma_centro_do_guilherme_periodo_1mes.log](https://github.com/user-attachments/files/18386701/ma_centro_do_guilherme_per …
> Atualiza raspadores para Centro do Guilherme e Maranhãozinho-MA

- data_collection/gazette/spiders/ma/ma_sao_luis.py
[ma_sao_luis_ultima.log](https://github.com/user-attachments/files/18392181/ma_sao_luis_ultima.log) | [ma_sao_luis_ultima.csv](https://github.com/user-attachments/files/18392182/ma_sao_luis_ultima.csv)
[ma_sao_luis_periodo_1ano.log](https://github.com/user-attachments/files/18392184/ma_sao_luis_periodo_1ano.log) | [ma_sao_luis_periodo_1ano.csv](https://github.com/user-attachments/files/18392185/ma_sao_luis_periodo_1ano.csv)
[ma_sao_luis_periodo_2meses.log](https://github.com/user-attachments/files/18392186/ma_sao_luis_periodo_2meses.log) | …
> Adiciona raspador para São Luís-MA

- data_collection/gazette/spiders/es/es_vitoria.py
Adiciona spider para Vitória, ES
> Add Vitória-ES spider

- data_collection/gazette/spiders/rj/rj_arraial_do_cabo.py
Novo spider customizado para Arraial do Cabo, conforme #1261. Eu mudei a data de início pois o registro mais antigo que eu consegui encontrar manualmente no site foi em `07/05/2019`.
```
scrapy crawl rj_arraial_do_cabo -a start_date=2024-09-20 -s LOG_FILE=rj_arraial_do_cabo.log -o rj_arraial_do_cabo.csv
```
- [rj_arraial_do_cabo.csv](https://github.com/user-attachments/files/17082584/rj_arraial_do_cabo.csv)
- [rj_arraial_do_cabo.log](https://github.com/user-attachments/files/17082585/rj_arraial_do_cabo.log)
```
scrapy crawl rj_arraial_do_cabo -a start_date=2024-09-01 -a end_date=2024-09-20 -s LOG_FILE=rj_arraial_do_cabo.log -o rj_arraial_do_cabo.csv
```
- [rj_arraial_do_cabo.csv](https://github.com/user-attachments/files/17082599/rj_arraial_do_cabo.csv) …
> Feature - Novo spider para Arraial do Cabo - RJ [Fixes #1261]

- data_collection/gazette/spiders/base/administracaopublica.py
- data_collection/gazette/spiders/ma/ma_nova_iorque.py
- data_collection/gazette/spiders/ma/ma_peritoro.py
- data_collection/gazette/spiders/ma/ma_turilandia.py
[ma_nova_iorque_arbitrario.csv](https://github.com/user-attachments/files/17263858/ma_nova_iorque_arbitrario.csv)
[ma_nova_iorque_arbitrario.log](https://github.com/user-attachments/files/17263859/ma_nova_iorque_arbitrario.log)
[ma_nova_iorque_completo.csv](https://github.com/user-attachments/files/17263860/ma_nova_iorque_completo.csv)
[ma_nova_iorque_completo.log](https://github.com/user-attachments/files/17263861/ma_nova_iorque_completo.log)
[ma_nova_iorque_mais_recente.log](https://github.com/user-attachments/files/17263862/ma_nova_iorque_mais_recente.log)
O sistema replicável …
> sistema replicavel administracaopublica #1247

- data_collection/gazette/spiders/pr/pr_juranda.py
[last_pr_juranda.txt](https://github.com/user-attachments/files/18564014/last_pr_juranda.txt)
[pr_juranda.txt](https://github.com/user-attachments/files/18564055/pr_juranda.txt)
[pr_juranda.csv](https://github.com/user-attachments/files/18564058/pr_juranda.csv)
[full_pr_juranda.csv](https://github.com/user-attachments/files/18564072/full_pr_juranda.csv)
[full_pr_juranda.txt](https://github.com/user-attachments/files/18564078/full_pr_juranda.txt)
Novo raspador para cidade de Juranda - Paraná
> Cria spider pr-juranda

- data_collection/gazette/spiders/base/ptio.py
- data_collection/gazette/spiders/rj/rj_areal.py
- data_collection/gazette/spiders/rj/rj_comendador_levy_gasparian.py
- data_collection/gazette/spiders/rj/rj_sapucaia.py
[log.zip](https://github.com/user-attachments/files/16922023/log.zip)
resolve #1113 
Cria base ptio e spiders para os municípios do RJ que estão mapeados na #1114 : Areal, Cabo Frio, Comendador Levy Gasparian e Sapucaia.
Obs1: Há diários com mesmo número de edição e data que não são edições extras, pois cada edição pode conter cadernos publicados em arquivos diferentes.
Para os 4 municípios tratados não foi possível localizar edições extras e todos são exclusivamente do executivo. Ao adicionar novos municípios mapeados na issue #1114, talvez seja necessário adaptar o código do …
> Cria base ptio e adiciona 3 municipios do RJ

- data_collection/gazette/spiders/rj/rj_itaguai.py
- 
[ultima.csv](https://github.com/user-attachments/files/18848636/ultima.csv)
[ultima.log](https://github.com/user-attachments/files/18848639/ultima.log)
[completa.csv](https://github.com/user-attachments/files/18848641/completa.csv)
[completa.log](https://github.com/user-attachments/files/18848644/completa.log)
[intervalo.csv](https://github.com/user-attachments/files/18848646/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/18848648/intervalo.log)
cria spider para rj_itaguai, resolve #1197 
os erros presentes nos log, são referentes a links quebrados no …
> Cria spider rj_itaguai 

- data_collection/gazette/spiders/rj/rj_itaguai.py
- data_collection/gazette/spiders/rj/rj_mesquita.py
- data_collection/gazette/spiders/rj/rj_miguel_pereira.py
- data_collection/gazette/spiders/rj/rj_quatis.py
- data_collection/gazette/spiders/rj/rj_queimados.py
- data_collection/gazette/spiders/rj/rj_sao_joao_de_meriti.py
- data_collection/gazette/spiders/rj/rj_sao_pedro_da_aldeia.py
Todos os raspadores em produção de BaseModernizacao não fazem sequer a primeira requisição, enquanto funciona normalmente em execução local. 
Parece ser um caso de bloqueio de IP estrangeiro
> Habilita proxy em raspadores de BaseModernizacao

- data_collection/gazette/spiders/rj/rj_duque_de_caxias.py
[completa.csv](https://github.com/user-attachments/files/18140374/completa.csv)
[completa.log](https://github.com/user-attachments/files/18140375/completa.log)
[intervalo.csv](https://github.com/user-attachments/files/18140376/intervalo.csv)
[intervalo.log](https://github.com/user-attachments/files/18140377/intervalo.log)
[ultima.csv](https://github.com/user-attachments/files/18140378/ultima.csv)
[ultima.log](https://github.com/user-attachments/files/18140379/ultima.log)
Resolve #616 
Atualiza o código do PR #705 para o padrão atual do projeto, coletando todos os atributos do …
> Cria spider para Duque de Caxias RJ no padrão atual do projeto

- data_collection/gazette/spiders/rs/rs_camaqua.py
<Descreva o seu Pull Request informando a issue (caso exista) que está sendo solucionada ou uma descrição do código apresentado>
Ajustando a aranha Camaquâ/RS para suportar o novo sistema de replicação AtendeV2. Issue [#1038](https://github.com/okfn-brasil/querido-diario/issues/1038)
[camaqua_rs-2025-07-07-2025-07-11.csv](https://github.com/user-attachments/files/21206750/camaqua_rs-2025-07-07-2025-07-11.csv)
[camaqua_rs-2025-07-07-2025-07-11.log](https://github.com/user-attachments/files/21206751/camaqua_rs-2025-07-07-2025-07-11.log) …
> Adjusting Camaquâ/RS spider to support new replicate system AtendeV2.

- data_collection/gazette/spiders/sp/sp_barueri.py
[sp_barueri_ultima_edicao.csv](https://github.com/user-attachments/files/21568113/sp_barueri_ultima_edicao.csv)
[log_sp_barueri_ultima_edicao.txt](https://github.com/user-attachments/files/21568114/log_sp_barueri_ultima_edicao.txt)
[log_sp_barueri_ano_2014.txt](https://github.com/user-attachments/files/21568150/log_sp_barueri_ano_2014.txt)
[sp_barueri_ano_2014.csv](https://github.com/user-attachments/files/21568154/sp_barueri_ano_2014.csv)
[sp_barueri_completo.csv](https://github.com/user-attachments/files/21568123/sp_barueri_completo.csv) …
> Adicionar raspador para Barueri SP
